#!/usr/bin/env bash
set -euo pipefail
exec </dev/null
source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

require_commands psql pg_dump
require_vars SOURCE_DATABASE_URL MIGRATION_ARTIFACT_DIR
start_log dump-source

schemas=(auth public realtime storage supabase_migrations swarm swarm_read)
schema_args=()
for schema in "${schemas[@]}"; do
  schema_args+=(--schema "$schema")
done

present="$({ source_psql --tuples-only --no-align --command \
  "SELECT nspname FROM pg_namespace WHERE nspname = ANY (string_to_array('$(selected_schema_csv)', ',')) ORDER BY nspname"; } 2>>"$LOG_FILE")"
expected="$(printf '%s\n' "${schemas[@]}" | LC_ALL=C sort)"
if [[ "$present" != "$expected" ]]; then
  log "required schema set is incomplete"
  exit 1
fi

roles_sql="$MIGRATION_ARTIFACT_DIR/roles.sql"
roles_query="$(make_temp_sql)"
counts_query="$(make_temp_sql)"
trap 'rm -f "$roles_query" "$counts_query"' EXIT

cat >"$roles_query" <<'SQL'
\pset tuples_only on
\pset format unaligned
WITH chosen AS (
  SELECT *
  FROM pg_roles
  WHERE rolname ~ '^(swarm_|commonswarm_)'
)
SELECT format(
  'DO $role$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = %L) THEN CREATE ROLE %I; END IF; END $role$;%sALTER ROLE %I WITH %s %s %s %s %s %s %s CONNECTION LIMIT %s;',
  rolname,
  rolname,
  E'\n',
  rolname,
  CASE WHEN rolsuper THEN 'SUPERUSER' ELSE 'NOSUPERUSER' END,
  CASE WHEN rolinherit THEN 'INHERIT' ELSE 'NOINHERIT' END,
  CASE WHEN rolcreaterole THEN 'CREATEROLE' ELSE 'NOCREATEROLE' END,
  CASE WHEN rolcreatedb THEN 'CREATEDB' ELSE 'NOCREATEDB' END,
  CASE WHEN rolcanlogin THEN 'LOGIN' ELSE 'NOLOGIN' END,
  CASE WHEN rolreplication THEN 'REPLICATION' ELSE 'NOREPLICATION' END,
  CASE WHEN rolbypassrls THEN 'BYPASSRLS' ELSE 'NOBYPASSRLS' END,
  rolconnlimit
)
FROM chosen
ORDER BY rolname;

SELECT format(
  'GRANT %I TO %I%s;',
  parent.rolname,
  member.rolname,
  CASE WHEN membership.admin_option THEN ' WITH ADMIN OPTION' ELSE '' END
)
FROM pg_auth_members AS membership
JOIN pg_roles AS parent ON parent.oid = membership.roleid
JOIN pg_roles AS member ON member.oid = membership.member
WHERE parent.rolname ~ '^(swarm_|commonswarm_)'
   OR member.rolname ~ '^(swarm_|commonswarm_)'
ORDER BY parent.rolname, member.rolname;

SELECT 'ALTER ROLE swarm_command SET search_path = swarm, pg_catalog;'
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'swarm_command');
SQL

{
  printf '%s\n' '-- Generated by dump-source.sh. No passwords are dumped.'
  source_psql --file "$roles_query"
} >"$roles_sql" 2>>"$LOG_FILE"
chmod 0600 "$roles_sql"
log "role definitions captured without password verifiers"

dump_file="$MIGRATION_ARTIFACT_DIR/database.dump"
PGDATABASE="$SOURCE_DATABASE_URL" pg_dump \
  --format=custom \
  --compress=6 \
  --file "$dump_file" \
  --no-publications \
  --no-subscriptions \
  --exclude-table-data=realtime.messages \
  "${schema_args[@]}" \
  >>"$LOG_FILE" 2>&1 </dev/null
chmod 0600 "$dump_file"
log "database dump captured selected schemas; realtime.messages data excluded"

cat >"$counts_query" <<'SQL'
\pset tuples_only on
\pset format unaligned
\pset fieldsep '|'
SELECT format(
  'SELECT %L, count(*)::bigint FROM %I.%I;',
  schemaname || '.' || tablename,
  schemaname,
  tablename
)
FROM pg_tables
WHERE schemaname = ANY (string_to_array('auth,public,realtime,storage,supabase_migrations,swarm,swarm_read', ','))
  AND NOT (schemaname = 'realtime' AND tablename = 'messages')
ORDER BY schemaname, tablename
\gexec
SQL

source_psql --file "$counts_query" >"$MIGRATION_ARTIFACT_DIR/source-counts.tsv" 2>>"$LOG_FILE"
chmod 0600 "$MIGRATION_ARTIFACT_DIR/source-counts.tsv"

source_psql --tuples-only --no-align --command \
  "SELECT json_build_object('bucket', bucket_id, 'name', name, 'content_type', COALESCE(metadata->>'mimetype', 'application/octet-stream')) FROM storage.objects WHERE bucket_id = 'swarm-files' ORDER BY name" \
  >"$MIGRATION_ARTIFACT_DIR/storage-objects.ndjson" 2>>"$LOG_FILE"
chmod 0600 "$MIGRATION_ARTIFACT_DIR/storage-objects.ndjson"

cat >"$MIGRATION_ARTIFACT_DIR/manifest.txt" <<EOF
format=commonswarm-n-db-v1
postgres_major=17
schemas=$(selected_schema_csv)
excluded_schema_data=realtime.messages
excluded_image_owned_schemas=_realtime,extensions,graphql_public,net,pgbouncer,supabase_functions,vault
storage_bucket=swarm-files
EOF
chmod 0600 "$MIGRATION_ARTIFACT_DIR/manifest.txt"

table_count="$(wc -l <"$MIGRATION_ARTIFACT_DIR/source-counts.tsv" | tr -d ' ')"
object_count="$(wc -l <"$MIGRATION_ARTIFACT_DIR/storage-objects.ndjson" | tr -d ' ')"
log "captured row counts for $table_count tables and a manifest for $object_count storage objects"
log "complete dump-source"
