#!/usr/bin/env bash
set -euo pipefail
exec </dev/null
source "$(cd "$(dirname "$0")" && pwd)/lib.sh"

origin="${1:-source}"
if [[ "$origin" != source && "$origin" != target && "$origin" != backup ]]; then
  echo "usage: dump-source.sh source|target|backup" >&2
  exit 64
fi
require_commands psql pg_dump
require_vars MIGRATION_ARTIFACT_DIR
# pg_dump below reads the service file directly, not through database_psql.
: "${PGSERVICEFILE:?run through run-db-tool.sh so database credentials stay in protected files}"
case "$origin" in
  source) require_vars SOURCE_DATABASE_URL ;;
  target) require_vars TARGET_DATABASE_URL ;;
  backup) : ;; # Protected backup service file carries no admin connection.
esac
start_log "dump-$origin"
assert_dump_origin "$origin"

schemas=(auth public realtime storage supabase_migrations swarm swarm_read)
schema_args=()
for schema in "${schemas[@]}"; do schema_args+=(--schema "$schema"); done

present="$({ database_psql "$origin" --tuples-only --no-align --command \
  "SELECT nspname FROM pg_namespace WHERE nspname = ANY (string_to_array('$(selected_schema_csv)', ',')) ORDER BY nspname"; } 2>>"$LOG_FILE")"
expected="$(printf '%s\n' "${schemas[@]}" | LC_ALL=C sort)"
if [[ "$present" != "$expected" ]]; then
  log "required schema set is incomplete"
  exit 1
fi

roles_sql="$MIGRATION_ARTIFACT_DIR/roles.sql"
roles_query="$(make_temp_sql)"
counts_query="$(make_temp_sql)"
objects_query="$(make_temp_sql)"
cron_query="$(make_temp_sql)"
holder_query="$(make_temp_sql)"
snapshot_file="$(mktemp "${TMPDIR:-/tmp}/commonswarm-snapshot.XXXXXX")"
snapshot_ready="$(mktemp "${TMPDIR:-/tmp}/commonswarm-snapshot-ready.XXXXXX")"
snapshot_release="$(mktemp "${TMPDIR:-/tmp}/commonswarm-snapshot-release.XXXXXX")"
rm -f "$snapshot_ready" "$snapshot_release"
holder_pid=""
cleanup() {
  touch "$snapshot_release" 2>/dev/null || true
  if [[ -n "$holder_pid" ]]; then wait "$holder_pid" 2>/dev/null || true; fi
  rm -f "$roles_query" "$counts_query" "$objects_query" "$cron_query" "$holder_query" \
    "$snapshot_file" "$snapshot_ready" "$snapshot_release"
}
trap cleanup EXIT

cat >"$roles_query" <<'SQL'
WITH chosen AS (
  SELECT * FROM pg_roles
  WHERE rolname ~ '^(swarm_|commonswarm_)' OR rolname = 'supabase_realtime_admin'
)
SELECT format(
  'DO $role$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = %L) THEN CREATE ROLE %I; END IF; END $role$;%sALTER ROLE %I WITH %s %s %s %s %s %s %s CONNECTION LIMIT %s;',
  rolname, rolname, E'\n', rolname,
  CASE WHEN rolsuper THEN 'SUPERUSER' ELSE 'NOSUPERUSER' END,
  CASE WHEN rolinherit THEN 'INHERIT' ELSE 'NOINHERIT' END,
  CASE WHEN rolcreaterole THEN 'CREATEROLE' ELSE 'NOCREATEROLE' END,
  CASE WHEN rolcreatedb THEN 'CREATEDB' ELSE 'NOCREATEDB' END,
  CASE WHEN rolcanlogin THEN 'LOGIN' ELSE 'NOLOGIN' END,
  CASE WHEN rolreplication THEN 'REPLICATION' ELSE 'NOREPLICATION' END,
  CASE WHEN rolbypassrls THEN 'BYPASSRLS' ELSE 'NOBYPASSRLS' END,
  rolconnlimit
)
FROM chosen ORDER BY rolname;

SELECT format('GRANT %I TO %I%s;', parent.rolname, member.rolname,
  CASE WHEN membership.admin_option THEN ' WITH ADMIN OPTION' ELSE '' END)
FROM pg_auth_members AS membership
JOIN pg_roles AS parent ON parent.oid = membership.roleid
JOIN pg_roles AS member ON member.oid = membership.member
WHERE parent.rolname ~ '^(swarm_|commonswarm_)'
   OR member.rolname ~ '^(swarm_|commonswarm_)'
   OR parent.rolname = 'supabase_realtime_admin'
   OR member.rolname = 'supabase_realtime_admin'
ORDER BY parent.rolname, member.rolname;

SELECT 'ALTER ROLE swarm_command SET search_path = swarm, pg_catalog;'
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'swarm_command');
SQL

{
  printf '%s\n' '-- Generated by dump-source.sh. No passwords are dumped.'
  database_psql "$origin" --tuples-only --no-align --file "$roles_query"
} >"$roles_sql" 2>>"$LOG_FILE"
chmod 0600 "$roles_sql"
log "role definitions captured without password verifiers"

cat >"$holder_query" <<SQL
BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;
\o $snapshot_file
SELECT pg_export_snapshot();
\o
\! touch $snapshot_ready; while [ ! -e $snapshot_release ]; do sleep 0.1; done
COMMIT;
SQL
database_psql "$origin" --tuples-only --no-align --file "$holder_query" >>"$LOG_FILE" 2>&1 &
holder_pid="$!"
for _ in $(seq 1 300); do
  [[ -s "$snapshot_file" && -e "$snapshot_ready" ]] && break
  kill -0 "$holder_pid" 2>/dev/null || { log "snapshot holder exited early"; exit 1; }
  sleep 0.1
done
if [[ ! -s "$snapshot_file" || ! -e "$snapshot_ready" ]]; then
  log "snapshot export timed out"
  exit 1
fi
snapshot="$(tr -d '[:space:]' <"$snapshot_file")"
if [[ ! "$snapshot" =~ ^[0-9A-F]+-[0-9A-F]+-[0-9]+$ ]]; then
  log "snapshot export returned an invalid identifier"
  exit 1
fi

dump_file="$MIGRATION_ARTIFACT_DIR/database.dump"
PGSERVICE="$origin" pg_dump \
  --dbname "service=$origin" \
  --snapshot "$snapshot" \
  --format=custom \
  --compress=6 \
  --file "$dump_file" \
  --no-publications \
  --no-subscriptions \
  --exclude-table=public.commonswarm_cutover_probe \
  --exclude-table=public.commonswarm_cutover_state \
  --exclude-table='realtime.messages_*' \
  --exclude-table-data=realtime.messages \
  "${schema_args[@]}" \
  >>"$LOG_FILE" 2>&1 </dev/null
chmod 0600 "$dump_file"

cat >"$counts_query" <<'SQL'
\getenv snapshot_id COMMONSWARM_EXPORTED_SNAPSHOT
BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET TRANSACTION SNAPSHOT :'snapshot_id';
SELECT format('SELECT %L, count(*)::bigint FROM %I.%I;',
  schemaname || '.' || tablename, schemaname, tablename)
FROM pg_tables
WHERE schemaname = ANY (string_to_array('auth,public,realtime,storage,supabase_migrations,swarm,swarm_read', ','))
  AND NOT (schemaname = 'realtime' AND (tablename = 'messages' OR tablename LIKE 'messages_%'))
  AND NOT (schemaname = 'public' AND tablename = 'commonswarm_cutover_probe')
  AND NOT (schemaname = 'public' AND tablename = 'commonswarm_cutover_state')
ORDER BY schemaname, tablename
\gexec
COMMIT;
SQL
COMMONSWARM_EXPORTED_SNAPSHOT="$snapshot" database_psql "$origin" \
  --quiet --tuples-only --no-align --field-separator '|' --file "$counts_query" \
  >"$MIGRATION_ARTIFACT_DIR/source-counts.tsv" 2>>"$LOG_FILE"
chmod 0600 "$MIGRATION_ARTIFACT_DIR/source-counts.tsv"

cat >"$objects_query" <<'SQL'
\getenv snapshot_id COMMONSWARM_EXPORTED_SNAPSHOT
BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET TRANSACTION SNAPSHOT :'snapshot_id';
SELECT json_build_object(
  'bucket', bucket_id,
  'name', name,
  'content_type', COALESCE(metadata->>'mimetype', 'application/octet-stream')
)
FROM storage.objects
WHERE bucket_id = 'swarm-files'
ORDER BY name;
COMMIT;
SQL
COMMONSWARM_EXPORTED_SNAPSHOT="$snapshot" database_psql "$origin" \
  --quiet --tuples-only --no-align --file "$objects_query" \
  >"$MIGRATION_ARTIFACT_DIR/storage-objects.ndjson" 2>>"$LOG_FILE"
chmod 0600 "$MIGRATION_ARTIFACT_DIR/storage-objects.ndjson"

# A nightly recovery set must retain the exact physical object versions from
# the same exported database snapshot, including every Storage bucket.
if [[ "$origin" == backup ]]; then
  cat >"$objects_query" <<'SQL'
\getenv snapshot_id COMMONSWARM_EXPORTED_SNAPSHOT
BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET TRANSACTION SNAPSHOT :'snapshot_id';
SELECT json_build_object('bucket', bucket_id, 'name', name, 'version', version)
FROM storage.objects ORDER BY bucket_id, name;
COMMIT;
SQL
  COMMONSWARM_EXPORTED_SNAPSHOT="$snapshot" database_psql backup \
    --quiet --tuples-only --no-align --file "$objects_query" \
    >"$MIGRATION_ARTIFACT_DIR/storage-backend-objects.ndjson" 2>>"$LOG_FILE"
  chmod 0600 "$MIGRATION_ARTIFACT_DIR/storage-backend-objects.ndjson"
fi

# The pg_cron schedules live in the cron schema, outside the selected-schema dump; restore-cron-jobs.sh recreates them.
{
  printf '%s\n' '\getenv snapshot_id COMMONSWARM_EXPORTED_SNAPSHOT'
  printf '%s\n' 'BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;'
  printf '%s\n' "SET TRANSACTION SNAPSHOT :'snapshot_id';"
  cron_jobs_json_sql
  printf '%s\n' 'COMMIT;'
} >"$cron_query"
COMMONSWARM_EXPORTED_SNAPSHOT="$snapshot" database_psql "$origin" \
  --quiet --tuples-only --no-align --file "$cron_query" \
  >"$MIGRATION_ARTIFACT_DIR/cron-jobs.ndjson" 2>>"$LOG_FILE"
chmod 0600 "$MIGRATION_ARTIFACT_DIR/cron-jobs.ndjson"

touch "$snapshot_release"
wait "$holder_pid"
holder_pid=""

cat >"$MIGRATION_ARTIFACT_DIR/manifest.txt" <<EOF
format=commonswarm-n-db-v2
origin=$origin
postgres_major=17
schemas=$(selected_schema_csv)
snapshot_consistency=pg_export_snapshot
excluded_schema_data=realtime.messages,realtime.messages_*
excluded_image_owned_schemas=_realtime,extensions,graphql_public,net,pgbouncer,supabase_functions,vault
storage_bucket=swarm-files
cron_jobs=cron-jobs.ndjson
EOF
chmod 0600 "$MIGRATION_ARTIFACT_DIR/manifest.txt"

table_count="$(wc -l <"$MIGRATION_ARTIFACT_DIR/source-counts.tsv" | tr -d ' ')"
object_count="$(wc -l <"$MIGRATION_ARTIFACT_DIR/storage-objects.ndjson" | tr -d ' ')"
cron_count="$(grep -c . "$MIGRATION_ARTIFACT_DIR/cron-jobs.ndjson" || true)"
log "one exported snapshot produced the dump, $table_count table counts, $object_count storage rows, and $cron_count cron jobs visible to the dump role"
log "complete dump-$origin"
