// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
export declare const ADMIN_RESOURCE = "https://api.commonswarm.com/admin";
export declare const ADMIN_REGISTRY_VERSION = 1;
export declare const ADMIN_ACCESS_TTL_SECONDS = 300;
export declare const ADMIN_REFRESH_MAX_LIFETIME_SECONDS = 2592000;
export declare const ADMIN_GRANT_TTL_SECONDS = 2592000;
export declare const ADMIN_READ_RATE_PER_HOUR: {
    readonly lineage: 120;
    readonly connection: 120;
    readonly account: 1000;
    readonly workspace: 1000;
};
export declare const ADMIN_MUTATION_RATE_PER_HOUR: {
    readonly lineage: 20;
    readonly connection: 20;
    readonly account: 60;
    readonly workspace: 60;
};
export declare const ADMIN_REFRESH_RATE_PER_HOUR = 20;
export declare const ADMIN_WORKSPACE_CREATE_PER_DAY = 20;
export declare const ADMIN_INVITATION_ISSUE_PER_DAY = 10;
export declare const ADMIN_WORKSPACES_CREATED_PER_GRANT = 10;
export declare const ADMIN_SEATS_PER_GRANT: {
    readonly live: 10;
    readonly total: 50;
};
export declare const ADMIN_INVITATIONS_PER_GRANT: {
    readonly total: 10;
    readonly live_agent: 5;
};
export declare const ADMIN_WORKER_CREDENTIAL_ISSUES_PER_GRANT = 50;
export declare const ADMIN_WORKER_RENEWAL_LIMITS: {
    readonly bearer_seconds: 3600;
    readonly horizon_seconds: 2592000;
    readonly successors_per_worker: 800;
    readonly successors_per_grant: 8000;
};
export declare const ADMIN_CONNECTION_ATTEMPTS_PER_GRANT = 50;
export declare const ADMIN_INVITATION_AND_ATTEMPT_TTL: {
    readonly member_seconds: 604800;
    readonly agent_min_seconds: 3600;
    readonly agent_max_seconds: 86400;
    readonly agent_seats: 10;
    readonly attempt_seconds: 86400;
};
export declare const ADMIN_EXISTING_RESOURCE_CEILINGS: {
    readonly owned_workspaces: 10;
    readonly members_and_invitations: 25;
    readonly principals: 50;
    readonly joins_per_person: 5;
    readonly joins_per_workspace: 20;
    readonly hosted_seats: 10;
};
export declare const ADMIN_SCOPE_REGISTRY: {
    readonly 'admin:read': readonly ["admin_read_metadata"];
    readonly 'workspaces:create': readonly ["admin_create_workspace"];
    readonly 'workspaces:archive': readonly ["admin_archive_workspace"];
    readonly 'seats:create': readonly ["admin_create_seat", "admin_provision_seat", "admin_replace_undelivered_seat_credential"];
    readonly 'seats:renew': readonly ["admin_renew_seat"];
    readonly 'seats:manage': readonly ["admin_set_seat_model", "admin_enable_seat_management", "admin_recover_seat_session"];
    readonly 'seats:revoke': readonly ["admin_revoke_seat", "admin_revoke_seat_credential"];
    readonly 'invites:create': readonly ["admin_invite_member", "admin_issue_agent_invitation"];
    readonly 'invites:revoke': readonly ["admin_revoke_invitation", "admin_revoke_agent_invitation"];
    readonly 'members:manage': readonly ["admin_remove_member", "admin_change_member_role"];
    readonly 'onboarding:connect': readonly ["admin_prepare_connection", "redeem_agent_connection", "record_agent_connection_progress", "admin_cancel_connection"];
};
export type AdminScope = keyof typeof ADMIN_SCOPE_REGISTRY;
export declare const ADMIN_SCOPE_NAMES: AdminScope[];
export declare const ADMIN_ISSUANCE_CEILINGS: {
    readonly workspaces: 10;
    readonly live_seats: 10;
    readonly total_seats: 50;
    readonly invitations: 10;
    readonly live_agent_invitations: 5;
    readonly worker_credentials: 50;
    readonly connection_attempts: 50;
};
export declare const ADMIN_RENEWAL_CEILINGS: {
    readonly bearer_seconds: 3600;
    readonly horizon_seconds: 2592000;
    readonly successors_per_worker: 800;
    readonly successors_per_grant: 8000;
};
export declare function adminRecord(value: unknown): Record<string, unknown> | null;
export declare function adminExactKeys(value: Record<string, unknown>, keys: readonly string[]): boolean;
export declare const ADMIN_UUID_RE: RegExp;
export declare function adminIds(value: unknown): value is string[];
export declare function adminScopes(value: unknown): value is AdminScope[];
export interface AdminManifest {
    admin_identity_id: string;
    connection_id: string;
    client_id: string;
    resource: typeof ADMIN_RESOURCE;
    mode: 'granular' | 'full_account';
    registry_version: typeof ADMIN_REGISTRY_VERSION;
    scope_names: AdminScope[];
    workspace_selector: 'selected' | 'owned_and_selected';
    workspace_ids: string[];
    created_workspace_policy: {
        scope_names: AdminScope[];
    };
    target_rules: {
        seat_ids: string[];
        own_seats: boolean;
        grant_created_seats: boolean;
        recipient_user_ids: string[];
        recipient_connection_ids: string[];
        transports: ('local' | 'hosted_mcp')[];
    };
    worker_scope_ceiling: string[];
    role_ceiling: 'member';
    renewal_limits: {
        grant_kinds: ('timeboxed' | 'standing')[];
        principal_ids: string[];
        bearer_seconds: number;
        horizon_seconds: number;
        successors_per_worker: number;
        successors_per_grant: number;
    };
    issuance_limits: {
        [K in keyof typeof ADMIN_ISSUANCE_CEILINGS]: number;
    };
    expires_at: number;
    refresh_deadline: number;
}
/** Validate untrusted JSON as well as typed callers; no missing limit means unlimited. */
export declare function adminManifestValid(value: unknown, now: number, initial?: boolean): value is AdminManifest;
/** The adapter hashes this canonical manifest; ordering never changes its meaning. */
export declare function canonicalAdminJson(value: unknown): string;
/** Project exactly the consent fields from a durable grant/event projection. */
export declare function adminGrantManifest(value: AdminManifest): AdminManifest;
