// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
export declare const ADMIN_ROUTINE_EVENT_TYPES: readonly ["AdminWorkspaceCreated", "AdminSeatCreated", "AdminSeatProvisioned", "AdminSeatRenewed", "AdminSeatCredentialReplaced", "AdminSeatRevoked", "AdminSeatCredentialRevoked", "AdminMemberInvited", "AdminAgentInvitationIssued", "AdminInvitationRevoked", "AdminMemberInvitationAccepted"];
export type AdminRoutineEventType = typeof ADMIN_ROUTINE_EVENT_TYPES[number];
