// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
import { type AdminRoutineState, type AdminRoutineEventType } from './admin-routine.d.ts';
import { type AdminManifest, type AdminScope } from './admin-policy.d.ts';
export type AdminActor = {
    kind: 'human';
    user_id: string;
    session_binding: string;
} | {
    kind: 'delegated_admin';
    admin_identity_id: string;
    grant_id: string;
    connection_id: string;
    scope_names: AdminScope[];
    access_expires_at: number;
    resource: string;
} | {
    kind: 'credential_runtime';
    connection_id: string;
    client_id: string;
    resource: string;
} | {
    kind: 'system';
} | {
    kind: 'worker' | 'hosted_seat';
};
export interface AdminConsent {
    consent_receipt_id: string;
    owner_user_id: string;
    session_binding: string;
    manifest_digest: string;
    manifest: AdminManifest;
    full_account_selected: boolean;
    expires_at: number;
    consumed_at: number | null;
}
export interface AdminGrant extends AdminManifest {
    grant_id: string;
    owner_user_id: string;
    consent_receipt_id: string;
    manifest_digest: string;
    created_at: number;
    state: 'active' | 'suspended' | 'revoked' | 'expired';
    suspended_at: number | null;
    revoked_at: number | null;
    reason_code: string | null;
    withdrawn_workspace_ids: string[];
}
export interface AdminCredentialLineage {
    credential_lineage_id: string;
    grant_id: string;
    generation: number;
    scope_names: AdminScope[];
    access_expires_at: number;
    refresh_deadline: number;
    state: 'active' | 'revoked';
    delivery_state: 'awaiting_delivery';
}
export interface AdminAccountState {
    client_approvals?: Record<string, AdminClientApproval>;
    connections?: Record<string, AdminConnectionAttempt>;
    routine?: AdminRoutineState;
    grants: Record<string, AdminGrant>;
    consents: Record<string, AdminConsent>;
    lineages: Record<string, AdminCredentialLineage>;
    rate_buckets: Record<string, {
        hour_start: number;
        attempts: number;
    }>;
}
export interface AdminClientApproval {
    owner_user_id: string;
    client_id: string;
    verification_version: number;
    approved_at: number;
    approval_event_id: string;
    approval_command_id: string;
    withdrawn_at: number | null;
    withdrawal_event_id: string | null;
    withdrawal_reason: string | null;
}
export interface AdminConnectionAttempt {
    attempt_id: string;
    parent_admin_grant_id: string;
    workspace_id: string;
    intended_owner_user_id: string;
    intended_agent_id: string;
    recipient_connection_id: string;
    requested_name: string;
    transport: 'local' | 'hosted_mcp';
    ttl_seconds: number;
    capability_set: string[];
    state: 'awaiting_authorization' | 'cancelled';
    created_at: number;
    expires_at: number;
    cancelled_at: number | null;
    reason_code: string | null;
}
export declare const ADMIN_EVENT_TYPES: readonly ["AdminConsentPrepared", "AdminDelegationGranted", "AdminDelegationNarrowed", "AdminDelegationRevoked", "AdminDelegationSuspended", "AdminDelegationExpired", "AdminWorkspaceAccessWithdrawn", "AdminCredentialIssued", "AdminCredentialRotated", "AdminCredentialReplayDetected", "AdminMetadataRead", "AdminActionRecorded", "AdminConnectionPrepared", "AdminConnectionCancelled", "AdminClientApproved", "AdminClientApprovalWithdrawn"];
export type AdminEventType = typeof ADMIN_EVENT_TYPES[number] | AdminRoutineEventType;
export interface AdminAccountEvent {
    stream_kind: 'account';
    owner_user_id: string;
    stream_id: string;
    seq: number;
    event_id: string;
    command_id: string;
    type: AdminEventType;
    schema_version: 1;
    actor_user: string | null;
    actor_agent_principal: null;
    actor_run: null;
    admin_identity_id: string | null;
    grant_id: string | null;
    grant_manifest_digest: string | null;
    occurred_at_server: number;
    payload: Record<string, unknown>;
}
export type AdminCommand = {
    kind: 'approve_admin_client';
    client_id: string;
    verification_version: number;
} | {
    kind: 'withdraw_admin_client_approval';
    client_id: string;
    verification_version: number;
    reason_code: string;
} | {
    kind: 'prepare_admin_consent';
    consent: AdminConsent;
} | {
    kind: 'grant_admin_delegation';
    grant_id: string;
    consent_receipt_id: string;
    replaces_grant_id: string | null;
} | {
    kind: 'narrow_admin_delegation';
    grant_id: string;
    manifest: AdminManifest;
    manifest_digest: string;
    consent_receipt_id: string;
} | {
    kind: 'revoke_admin_delegation' | 'suspend_admin_delegation' | 'surrender_admin_delegation';
    grant_id: string;
    reason_code: string;
} | {
    kind: 'expire_admin_delegation';
    grant_id: string;
} | {
    kind: 'withdraw_admin_workspace_access';
    grant_id: string;
    workspace_id: string;
    reason_code: string;
} | {
    kind: 'issue_admin_credential';
    grant_id: string;
    credential_lineage_id: string;
} | {
    kind: 'rotate_admin_credential' | 'record_admin_credential_replay';
    grant_id: string;
    credential_lineage_id: string;
    generation: number;
    scope_names: AdminScope[];
} | {
    kind: 'admin_read_metadata';
    grant_id: string;
    resource_kind: 'grant';
    workspace_id: string | null;
};
export interface AdminDecisionContext {
    actor: AdminActor;
    owner_user_id: string;
    now: number;
    command_id: string;
    stream_id: string;
    request_digest: string;
    nextSeq(): number;
    nextEventId(): string;
    current_workspace_rights: boolean;
    withdrawing_workspace_owner: boolean;
    target_workspace_owned_by_grantor: boolean;
    presenting_refresh_generation: number | null;
    presenting_refresh_lineage_id: string | null;
    client_policy?: {
        client_id: string;
        verification_version: number;
        verification_active: boolean;
        approval: AdminClientApproval | null;
        linked_grant_ids: readonly string[];
    };
}
export interface AdminDecision {
    ok: boolean;
    reason: string | null;
    events: AdminAccountEvent[];
}
export declare function emptyAdminAccount(): AdminAccountState;
/** Shared strict wire validation; these commands never accept an owner or verification facts. */
export declare function parseAdminClientApprovalCommand(input: unknown): Extract<AdminCommand, {
    client_id: string;
}> | null;
/** Shared counter keys and ceilings, including identifiable refused attempts. */
export declare function adminRatePolicy(actor: AdminActor, grant: AdminGrant, action: string, workspaceId: string | null, lineageId: string | null, requestedGrantId: string | null): {
    key: string;
    limit: number;
}[];
/** Account-only decisions. No routine admin operation is enabled by lane B. */
export declare function decideAdminAuthority(command: AdminCommand, state: AdminAccountState, ctx: AdminDecisionContext): AdminDecision;
/** Consent session bindings are separate private adapter facts, excluded from canonical events. */
export declare function reduceAdminAuthority(previous: AdminAccountState | null, event: AdminAccountEvent): AdminAccountState;
