// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
import type { AdminAccountEvent, AdminAccountState, AdminDecision, AdminDecisionContext } from "./admin-authority.d.ts";
import { type AdminScope } from "./admin-policy.d.ts";
import type { WorkspaceEventEnvelope, WorkspaceState } from "./workspace-events.d.ts";
export { ADMIN_ROUTINE_EVENT_TYPES, type AdminRoutineEventType, } from "./admin-routine-events.d.ts";
interface Base {
    grant_id: string;
    workspace_id: string;
}
export type AdminRoutineCommand = Base & ({
    kind: "admin_create_workspace";
    name: string;
} | {
    kind: "admin_create_seat";
    name: string;
    model: string | null;
    transport: "local" | "hosted_mcp";
} | {
    kind: "admin_provision_seat";
    principal_id: string;
    recipient_connection_id: string;
    worker_scope_names: string[];
    bearer_seconds: number;
    horizon_seconds: number;
    max_successors: number;
} | {
    kind: "admin_renew_seat";
    principal_id: string;
    predecessor_credential_id: string;
    recipient_connection_id: string;
    worker_scope_names: string[];
    bearer_seconds: number;
} | {
    kind: "admin_replace_undelivered_seat_credential";
    principal_id: string;
    credential_id: string;
    recipient_connection_id: string;
} | {
    kind: "admin_revoke_seat";
    principal_id: string;
    reason_code: string;
} | {
    kind: "admin_revoke_seat_credential";
    principal_id: string;
    credential_id: string;
    reason_code: string;
} | {
    kind: "admin_invite_member";
    recipient_user_id: string;
    role: "member";
    ttl_seconds: number;
} | {
    kind: "admin_issue_agent_invitation";
    intended_owner_user_id: string;
    recipient_connection_id: string;
    transport: "local" | "hosted_mcp";
    seat_limit: number;
    worker_scope_names: string[];
    ttl_seconds: number;
} | {
    kind: "admin_revoke_invitation" | "admin_revoke_agent_invitation";
    invitation_id: string;
    reason_code: string;
});
export interface RoutineCredential {
    credential_id: string;
    workspace_id: string;
    principal_id: string;
    worker_lineage_id: string;
    parent_admin_grant_id: string | null;
    recipient_connection_id: string;
    worker_scope_names: string[];
    expires_at: number;
    horizon_expires_at: number | null;
    bearer_seconds: number;
    max_successors: number | null;
    successors_used: number;
    kind: "timeboxed" | "standing";
    revoked_at: number | null;
    first_used_at: number | null;
    superseded: boolean;
    suspended: boolean;
    device_valid: boolean;
    run_id: string;
    task_id: string;
    epoch: number;
    renewal_grant_id: string;
    device_id: string;
}
export interface RoutineInvitation {
    invitation_id: string;
    workspace_id: string;
    parent_admin_grant_id: string;
    invitation_kind: "member" | "agent";
    recipient_user_id: string;
    recipient_connection_id: string | null;
    expires_at: number;
    revoked_at: number | null;
    accepted_at: number | null;
}
export interface AdminRoutineState {
    spend: Record<string, {
        workspaces: number;
        total_seats: number;
        invitations: number;
        worker_credentials: number;
        successors: number;
    }>;
    created_workspaces: Record<string, {
        grant_id: string;
        scope_names: AdminScope[];
    }>;
    seats: Record<string, {
        grant_id: string;
        workspace_id: string;
        revoked_at: number | null;
    }>;
    credentials: Record<string, RoutineCredential>;
    invitations: Record<string, RoutineInvitation>;
}
export declare const emptyAdminRoutine: () => AdminRoutineState;
export interface AdminRoutineContext extends AdminDecisionContext {
    workspace: WorkspaceState | null;
    workspace_stream_id: string;
    workspace_seq: number;
    owned_workspaces: number;
    workspace_creations_last_day: number;
    invitations_last_day: number;
    live_principals: number;
    live_members_and_invitations: number;
    live_agent_invitations_person: number;
    live_agent_invitations_workspace: number;
    human_worker_scopes: string[];
    recipient_exists: boolean;
    recipient_is_member: boolean;
    delivery_connection_id: string | null;
    target_credential: RoutineCredential | null;
    principal_lineage_ids: string[];
    nextResourceId(): string;
}
export interface AdminRoutineDecision extends AdminDecision {
    workspace_events: WorkspaceEventEnvelope[];
}
export declare function parseAdminRoutineCommand(value: unknown): AdminRoutineCommand | null;
/** No human impersonation and no I/O: both projections and budgets come from events. */
export declare function decideAdminRoutine(command: AdminRoutineCommand, account: AdminAccountState, ctx: AdminRoutineContext): AdminRoutineDecision;
export declare function reduceAdminRoutine(previous: AdminRoutineState | undefined, event: AdminAccountEvent): AdminRoutineState;
