// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
/** Current schema version for every task/lease event type. */
export declare const SCHEMA_VERSION = 1;
/**
 * A principal is the authoritative actor identity, derived server-side from a
 * credential (§2.1 — never from request fields). A worker acts as its agent
 * principal; a human acts as their user. `canonicalPrincipal` collapses an
 * Actor to the single stable string used for ownership comparison.
 */
export interface Actor {
    user: string | null;
    agent_principal: string | null;
    run: string | null;
}
/** The owner-of-record identity: the agent principal if present, else the user. */
export declare function canonicalPrincipal(actor: Actor): string;
/** Canonical event envelope (§2.1). `payload` is the per-type body below. */
export interface EventEnvelope<P = unknown, T extends string = EventType> {
    workspace_id: string;
    stream_id: string;
    /** Monotonic per-stream sequence. Events fold in ascending seq. */
    seq: number;
    event_id: string;
    /** The command that produced this event (idempotency + provenance). */
    command_id: string;
    type: T;
    schema_version: number;
    actor_user: string | null;
    actor_agent_principal: string | null;
    actor_run: string | null;
    /** Server time (ms epoch). Never client-supplied (§2.1/§4 honest-liveness). */
    occurred_at_server: number;
    /** Present only on server-derived delegated administration events. */
    admin_identity_id?: string | null;
    grant_id?: string | null;
    grant_manifest_digest?: string | null;
    payload: P;
}
export type EventType = 'TaskCreated' | 'LeaseAcquired' | 'LeaseRenewed' | 'LeaseHandedOff' | 'LeaseTakenOver' | 'TaskSubmitted' | 'TaskClosed' | 'TaskReopened' | 'CommandRejected';
export declare const EVENT_TYPES: readonly EventType[];
export interface TaskCreated {
    task_id: string;
    slug: string;
}
export interface LeaseAcquired {
    task_id: string;
    epoch: number;
    owner: string;
    lease_expiry: number;
}
export interface LeaseRenewed {
    task_id: string;
    epoch: number;
    lease_expiry: number;
}
export interface LeaseHandedOff {
    task_id: string;
    epoch: number;
    from_owner: string;
    to_owner: string;
    lease_expiry: number;
}
export interface LeaseTakenOver {
    task_id: string;
    epoch: number;
    owner: string;
    lease_expiry: number;
    grant_id: string | null;
}
export interface TaskSubmitted {
    task_id: string;
    epoch: number;
    branch: string;
    head_sha: string;
    evidence_set: string[];
}
export interface TaskClosed {
    task_id: string;
    epoch: number;
    disposition: string;
    grant_id: string | null;
}
export interface TaskReopened {
    task_id: string;
    version: number;
}
/** A committed domain rejection (§2.1 — authz failures are NOT events; these are). */
export interface CommandRejected {
    task_id: string;
    command: string;
    /** Machine-stable rejection code; see RejectionReason. */
    reason: RejectionReason;
    /** Human-facing, already treated as data (control chars stripped at render). */
    detail: string;
}
export type RejectionReason = 'slug_not_unique' | 'not_acquirable' | 'not_owner' | 'stale_epoch' | 'lease_expired' | 'recipient_not_member' | 'live_lease_needs_grant' | 'grant_invalid' | 'evidence_incomplete' | 'not_submitted' | 'close_needs_grant' | 'already_done' | 'unknown_task' | 'bad_state';
export type TaskLifecycle = 'open' | 'active' | 'awaiting_review' | 'reopened' | 'done';
/** Frozen on submit; survives lease expiry; invalidated by reopen / superseded by a new submit (§2.2). */
export interface Submission {
    epoch: number;
    branch: string;
    head_sha: string;
    evidence_set: string[];
}
export interface TaskState {
    task_id: string;
    slug: string;
    lifecycle: TaskLifecycle;
    /** Task version — bumped on reopen; invalidates prior submissions/grants (§2.2). */
    version: number;
    /** Lease epoch — 0 means never acquired. Incremented on acquire/handoff/takeover. */
    epoch: number;
    owner: string | null;
    lease_expiry: number | null;
    submission: Submission | null;
    closed_disposition: string | null;
}
/** True iff the lease is currently held and unexpired at `now`. */
export declare function leaseLive(state: TaskState, now: number): boolean;
