// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
export declare const HOUSEHOLD_OBJECT_LIMIT = 500;
export declare const HOUSEHOLD_STORAGE_BYTE_LIMIT: number;
export declare const HOUSEHOLD_VERSION_BYTE_LIMIT: number;
export declare const HOUSEHOLD_LIVE_REVISION_LIMIT = 20;
export declare const HOUSEHOLD_IDENTITY_WRITE_HOURLY_LIMIT = 600;
export declare const HOUSEHOLD_WORKSPACE_WRITE_HOURLY_LIMIT = 2000;
/** Also used by consent and tool generation during lane 4 integration. */
export declare const HOUSEHOLD_CONTENT_OPERATIONS: readonly ["read", "create", "update"];
export type HouseholdContentOperation = typeof HOUSEHOLD_CONTENT_OPERATIONS[number];
export declare const HOUSEHOLD_CONTENT_ROLES: readonly ["reader", "editor"];
export type HouseholdContentRole = typeof HOUSEHOLD_CONTENT_ROLES[number];
export interface HouseholdMemberFacts {
    user_id: string;
    workspace_id: string;
    revoked_at: number | null;
    content_role: HouseholdContentRole | null;
    /** A human-confirmed receipt, never inferred from an administrative role. */
    content_consent_id: string | null;
}
export interface HouseholdConnectionFacts {
    principal_id: string;
    owner_user_id: string;
    workspace_id: string;
    connection_id: string;
    grant_id: string;
    revoked_at: number | null;
    /** NULL approvals last until withdrawn; local approvals retain token expiry. */
    expires_at: number | null;
    operations: readonly HouseholdContentOperation[];
    /** Private/shared purposes use different connections and principals. */
    purpose: 'personal' | 'shared';
}
/** Authenticated, transaction-locked facts. Never construct these from a request. */
export interface HouseholdAccessFacts {
    workspace_id: string;
    archived_at: number | null;
    boundary: {
        kind: 'shared';
    } | {
        kind: 'personal';
        owner_user_id: string;
    };
    actor: {
        user_id: string;
        principal_id: string | null;
        run_id: string | null;
    };
    credential: {
        kind: 'human';
    } | {
        kind: 'agent';
        connection: HouseholdConnectionFacts;
    };
    member: HouseholdMemberFacts | null;
}
export type HouseholdAccessRefusal = 'workspace_access_refused' | 'content_consent_required' | 'content_read_only' | 'connection_access_refused';
/** Administration, relationships, seat names and content cannot expand this check. */
export declare function householdAccessRefusal(facts: HouseholdAccessFacts, workspaceId: string, operation: HouseholdContentOperation, now: number): HouseholdAccessRefusal | null;
/** Attempts include validated refusals; the adapter charges the durable bucket once. */
export declare function householdWriteLimitReached(identityAttempts: number, workspaceAttempts: number): boolean;
