// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
import { type EventEnvelope } from './events.d.ts';
import { type HouseholdAccessFacts, type HouseholdAccessRefusal } from './household-object-policy.d.ts';
export type Party = {
    kind: 'user';
    id: string;
} | {
    kind: 'agent';
    id: string;
};
export interface TodoActor {
    user_id: string;
    principal_id: string | null;
}
export type TodoState = 'open' | 'doing' | 'done' | 'dropped';
export type TodoStart = 'queue' | 'now';
export type TodoGate = {
    kind: 'none';
} | {
    kind: 'hold';
    note: string | null;
} | {
    kind: 'after';
    todo_id: string;
} | {
    kind: 'at';
    at: string;
};
export interface TodoOffer {
    offer_id: string;
    to: Party;
    decider_user_id: string;
    start: TodoStart;
    gate: TodoGate;
    by: TodoActor;
    at: string;
}
/** Stored fields only. gate_clear and queue_position are derived on read. */
export interface Todo {
    workspace_id: string;
    todo_id: string;
    version: number;
    title: string;
    notes: string;
    state: TodoState;
    due_on: string | null;
    created_by: TodoActor;
    created_at: string;
    assignee: Party | null;
    assigned_by: TodoActor | null;
    assigned_at: string | null;
    offer: TodoOffer | null;
    gate: TodoGate;
    gate_set_by: string | null;
    queue_rank: number | null;
    state_by: TodoActor;
    state_at: string;
    comment_count: number;
}
export type CommentTarget = {
    kind: 'todo';
    id: string;
} | {
    kind: 'list' | 'doc' | 'file';
    id: string;
};
export interface TodoComment {
    comment_id: string;
    target: CommentTarget;
    author: TodoActor;
    body: string;
    mentions: readonly Party[];
    created_at: string;
}
export interface AgentWorkPolicy {
    principal_id: string;
    accepts_from: 'owner' | 'anyone';
    set_by_user: string;
    set_at: string;
}
export type TodoRefusal = HouseholdAccessRefusal | 'human_confirmation_required' | 'todo_not_found' | 'target_not_found' | 'title_invalid' | 'notes_invalid' | 'due_invalid' | 'comment_invalid' | 'mentions_invalid' | 'assignee_not_member' | 'assignee_removed' | 'invalid_transition' | 'not_assignee' | 'not_permitted' | 'owner_only' | 'offer_not_pending' | 'not_decider' | 'not_in_queue' | 'gate_invalid' | 'gate_cycle' | 'queue_empty' | 'queue_full' | 'todo_limit_reached' | 'request_id_reused' | 'todo_write_rate_limited' | 'invalid_command_context';
export type TodoOutcome = {
    status: 'committed';
    value: Todo | TodoComment | AgentWorkPolicy;
} | {
    status: 'conflict';
    current: Todo;
} | {
    status: 'refused';
    reason: TodoRefusal;
};
export interface TodoReceipt {
    principal: string;
    command_id: string;
    request_digest: string;
    outcome: TodoOutcome;
}
/** An intent, not a delivery claim. The adapter returns sent/not_sent receipts. */
export interface TodoNotice {
    kind: 'ask' | 'note';
    to: readonly Party[];
    about: string;
    body: string;
}
export declare const TODO_EVENT_TYPES: readonly ["TodoCreated", "TodoDetailsChanged", "TodoAssigned", "TodoOffered", "TodoOfferAnswered", "TodoStateChanged", "TodoQueueOrdered", "TodoGateSet", "TodoStartAsked", "TodoCommented", "AgentWorkPolicySet"];
export type TodoEventType = typeof TODO_EVENT_TYPES[number];
type TodoPayloads = {
    TodoCreated: {
        todo: Todo;
    };
    TodoDetailsChanged: {
        todo: Todo;
    };
    TodoAssigned: {
        todo: Todo;
    };
    TodoOffered: {
        todo: Todo;
    };
    TodoOfferAnswered: {
        todo: Todo;
        offer_id: string;
        answer: 'accept' | 'decline' | 'withdraw' | 'replaced';
    };
    TodoStateChanged: {
        todo: Todo;
    };
    TodoQueueOrdered: {
        principal_id: string;
        todo_ids: readonly string[];
    };
    TodoGateSet: {
        todo: Todo;
    };
    TodoStartAsked: {
        todo_id: string;
        principal_id: string;
    };
    TodoCommented: {
        comment: TodoComment;
        todo: Todo | null;
    };
    AgentWorkPolicySet: {
        policy: AgentWorkPolicy;
    };
};
export type TodoEvent = {
    [K in TodoEventType]: EventEnvelope<TodoPayloads[K] & {
        receipt?: TodoReceipt;
    }, K>;
}[TodoEventType];
export interface HouseholdTodoState {
    workspace_id: string;
    stream_id: string;
    last_seq: number;
    todos: Readonly<Record<string, Todo>>;
    comments: Readonly<Record<string, TodoComment>>;
    policies: Readonly<Record<string, AgentWorkPolicy>>;
    receipts: Readonly<Record<string, TodoReceipt>>;
}
export interface AssignInput {
    to: Party;
    start?: TodoStart;
    gate?: TodoGate;
}
export type SteerAction = {
    kind: 'move';
    after_todo_id: string | null;
} | {
    kind: 'start_now';
} | {
    kind: 'gate';
    gate: TodoGate;
};
export type TodoCommand = {
    kind: 'todo_create';
    title: string;
    notes?: string;
    due_on?: string | null;
    assign?: AssignInput;
} | {
    kind: 'todo_update';
    todo_id: string;
    base_version: number;
    title?: string;
    notes?: string;
    due_on?: string | null;
} | {
    kind: 'todo_assign';
    todo_id: string;
    base_version: number;
    to: Party | null;
    start?: TodoStart;
    gate?: TodoGate;
} | {
    kind: 'todo_start';
    todo_id?: string;
} | {
    kind: 'todo_set_state';
    todo_id: string;
    base_version: number;
    state: TodoState;
} | {
    kind: 'household_todo_answer';
    todo_id: string;
    offer_id: string;
    answer: 'accept' | 'decline' | 'withdraw';
} | {
    kind: 'household_todo_steer';
    todo_id: string;
    base_version: number;
    action: SteerAction;
} | {
    kind: 'household_agent_work_policy';
    principal_id: string;
    accepts_from: 'owner' | 'anyone';
} | {
    kind: 'todo_comment';
    target: CommentTarget;
    body: string;
    mentions?: readonly Party[];
};
export interface TodoMemberFacts {
    user_id: string;
    workspace_id: string;
    revoked_at: number | null;
    role: 'owner' | 'admin' | 'member';
}
export interface TodoAgentFacts {
    principal_id: string;
    owner_user_id: string;
    workspace_id: string;
    revoked_at: number | null;
}
export interface DecideTodoContext {
    access: HouseholdAccessFacts;
    now: number;
    command_id: string;
    request_digest: string;
    seq: number;
    /** One distinct server-generated UUID per emitted event, in order. */
    event_ids: readonly string[];
    todo_id?: string;
    offer_id?: string;
    comment_id?: string;
    members: readonly TodoMemberFacts[];
    agents: readonly TodoAgentFacts[];
    /** Current committed object identities for comment targets, not drafts. */
    objects: readonly {
        kind: 'list' | 'doc' | 'file';
        id: string;
    }[];
    identity_write_attempts: number;
    workspace_write_attempts: number;
}
export interface TodoDecision {
    outcome: TodoOutcome;
    events: readonly TodoEvent[];
    receipt: TodoReceipt | null;
    notices: readonly TodoNotice[];
    replayed: boolean;
}
/** No scheduler: time/dependency gates are evaluated against the read clock.
 * Even a corrupt cyclic projection fails closed. Missing dependencies stay held. */
export declare function evaluateGate(gate: TodoGate, todos: Readonly<Record<string, Todo>>, now: number): boolean;
export declare function emptyHouseholdTodoState(workspaceId: string, streamId: string): HouseholdTodoState;
export declare function decideTodo(state: HouseholdTodoState, command: TodoCommand, ctx: DecideTodoContext): TodoDecision;
/** Refused/conflicting/no-op commands have no event. The adapter must load their
 * durable receipts into state.receipts as well as the receipts replayed here. */
export declare function reduceTodoEvents(initial: HouseholdTodoState, events: readonly TodoEvent[]): HouseholdTodoState;
export {};
