// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
/** Human enrollment decisions. Inviting grants no right to choose the recipient's
 * content role, private workspace, connector, or agent identity. */
export declare const HOUSEHOLD_JOIN_RATE_PER_HOUR = 120;
export declare const HOUSEHOLD_JOIN_CONSENT_VERSION = "household-join-v1";
export declare const HOUSEHOLD_JOIN_DISCLOSURE = "Members can read shared workspace content and retained history, except directed messages restricted to their audience. Your personal and business spaces stay separate. You choose and authorize your own agents separately. Copies already read cannot be recalled.";
export type HumanInviteRef = {
    source: 'delegated';
    invitation_id: string;
} | {
    source: 'link';
    token: string;
};
export type HumanInviteCommand = {
    kind: 'household_invitation';
    action: 'preview';
    invitation: HumanInviteRef;
} | {
    kind: 'household_invitation';
    action: 'accept';
    invitation: HumanInviteRef;
    consent_version: string;
    preview_digest: string;
    content_role: 'reader' | 'editor';
};
export declare function parseHumanInviteCommand(value: unknown): HumanInviteCommand | null;
export interface HumanInviteFacts {
    human: boolean;
    identity_verified: boolean;
    recipient_matches: boolean;
    invitation_kind: 'member' | 'agent';
    role: string;
    personal_boundary: boolean;
    inviter_can_invite: boolean;
    parent_live: boolean;
    now: number;
    expires_at: number;
    revoked_at: number | null;
    accepted_at: number | null;
    accepted_by: string | null;
    user_id: string;
    member_live: boolean;
    preview_digest: string;
    /** Null when this person has no membership row, or that row is still live. */
    membership_revoked_at: number | null;
    invitation_created_at: number;
}
export type LegacyHouseholdAcceptRefusal = 'invitation_recipient_mismatch' | 'recipient_consent_required';
/** When a household boundary exists, legacy acceptance requires the verified email to equal the invited email. */
export declare function legacyHouseholdAcceptRefusal(boundaryPresent: boolean, verifiedEmail: string | null, invitedEmail: string | null): LegacyHouseholdAcceptRefusal | null;
export type LegacyRemovalRejoinRefusal = 'invitation_predates_removal';
/** A legacy invitation issued after the latest removal may rejoin. One issued at
 * or before that removal, or with no usable time, may not. */
export declare function legacyRemovalRejoinRefusal(membershipRevokedAt: number | null, invitationCreatedAt: number): LegacyRemovalRejoinRefusal | null;
export type HumanInviteDecision = {
    status: 'preview' | 'join' | 'already_joined';
} | {
    status: 'refused';
    reason: string;
};
export declare function decideHumanInvite(command: HumanInviteCommand, facts: HumanInviteFacts): HumanInviteDecision;
