// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
import { type HouseholdAccessFacts } from './household-object-policy.d.ts';
import { type HouseholdBlob, type HouseholdContent, type HouseholdDraft, type HouseholdObjectEvent, type HouseholdObjectState, type HouseholdOutcome, type HouseholdPatch, type HouseholdRevision, type HouseholdRevisionRef } from './household-object-events.d.ts';
export type HouseholdObjectCommand = {
    kind: 'create_household_object';
    object_id: string;
    title: string;
    content: HouseholdContent;
} | {
    kind: 'update_household_object';
    object_id: string;
    base: HouseholdRevisionRef;
    patch: HouseholdPatch;
    title?: {
        before: string;
        after: string;
    };
} | {
    kind: 'reserve_household_upload';
    object_id: string;
    reservation_id: string;
    expires_at: number;
    change: {
        kind: 'create';
        title: string;
        content: HouseholdContent;
    } | {
        kind: 'update';
        base: HouseholdRevisionRef;
        patch: HouseholdPatch;
        title?: {
            before: string;
            after: string;
        };
    };
} | {
    kind: 'commit_household_upload';
    reservation_id: string;
    operation: 'create' | 'update';
} | {
    kind: 'release_household_upload';
    reservation_id: string;
    operation: 'create' | 'update';
};
/** Adapter-verified artifact facts, never a client's size/digest attestation.
 * For list/docs the blob is the canonical encoding of content. For files it is
 * the actual file bytes, with verified metadata in content. No URLs or paths
 * supplied by models are fetched by this core.
 */
export interface HouseholdVerifiedContent {
    workspace_id: string;
    object_id: string;
    revision: HouseholdRevisionRef | null;
    blob: HouseholdBlob;
    content: HouseholdContent;
}
export interface DecideHouseholdObjectContext {
    access: HouseholdAccessFacts;
    now: number;
    command_id: string;
    /** Canonical request hash verified by the adapter, excluding server facts. */
    request_digest: string;
    seq: number;
    event_id: string;
    /** Generated by the server, not a client integer or content hash. */
    revision_token: string;
    draft_id: string;
    /** Includes this workspace's other retained bytes and unpurged names (legacy
     * files/tombstones included), not represented by this new projection yet. */
    other_storage_bytes: number;
    other_object_count: number;
    /** Counts BEFORE this attempt. The adapter charges validated version-create
     * attempts under the same lock, including refusals, but not retry recovery or
     * commit/release of an already charged reservation. */
    identity_write_attempts: number;
    workspace_write_attempts: number;
    /** Exact base snapshots loaded under current authorization. */
    contents: readonly HouseholdVerifiedContent[];
    /** Staged bytes verified by the adapter; commit loads the reservation's blob. */
    prepared: HouseholdVerifiedContent | null;
}
export interface HouseholdObjectDecision {
    outcome: HouseholdOutcome;
    events: readonly HouseholdObjectEvent[];
    replayed: boolean;
}
export declare function emptyHouseholdObjectState(workspaceId: string, streamId: string): HouseholdObjectState;
/** Includes ALL history and declarations; no expiry/retirement discounts before
 * an explicit release. A pending create reserves an unpurged-name slot. */
export declare function householdObjectUsage(state: HouseholdObjectState): {
    object_count: number;
    storage_bytes: number;
};
/** Apply an explicit patch to its exact base. Before values defeat a stale
 * replacement with a superficially current revision stapled onto it. Splices
 * are non-overlapping UTF-16 offsets into the base, never sequential offsets.
 */
export declare function applyHouseholdPatch(base: HouseholdContent, patch: HouseholdPatch, blob: HouseholdBlob): HouseholdContent | null;
export declare function decideHouseholdObject(command: HouseholdObjectCommand, state: HouseholdObjectState, ctx: DecideHouseholdObjectContext): HouseholdObjectDecision;
/** Deterministic replay validates continuity rather than trusting projections.
 * Permission is checked at decision/read time against durable current facts;
 * replay must not erase committed history when a member is later revoked. */
export declare function reduceHouseholdObject(state: HouseholdObjectState, event: HouseholdObjectEvent): HouseholdObjectState;
export declare function reduceHouseholdObjectStream(events: readonly HouseholdObjectEvent[], initial: HouseholdObjectState): HouseholdObjectState;
export type HouseholdReadQuery = {
    kind: 'object_list';
    offset: number;
    limit: number;
} | {
    kind: 'object_read';
    object_id: string;
    revision?: HouseholdRevisionRef;
} | {
    kind: 'object_history';
    object_id: string;
    offset: number;
    limit: number;
} | {
    kind: 'draft_read';
    draft_id: string;
};
export type HouseholdReadResult = {
    status: 'refused';
    reason: string;
} | {
    status: 'ok';
    kind: 'object_list';
    objects: readonly {
        object_id: string;
        kind: HouseholdContent['kind'];
        title: string;
        revision: HouseholdRevisionRef;
    }[];
    next_offset: number | null;
} | {
    status: 'ok';
    kind: 'object_read';
    revision: HouseholdRevision;
    live: boolean;
} | {
    status: 'ok';
    kind: 'object_history';
    revisions: readonly (HouseholdRevision & {
        live: boolean;
    })[];
    next_offset: number | null;
} | {
    status: 'ok';
    kind: 'draft_read';
    draft: HouseholdDraft;
};
/** Authorized read MODEL only. Byte routes must recheck these same facts at use,
 * then load the returned immutable blob. A reference is not a transfer token.
 * Pagination limits are provided by the measured adapter; v1 does not invent
 * unmeasured read/egress limits. No counts or names leak before authorization.
 */
export declare function readHouseholdObjects(query: HouseholdReadQuery, state: HouseholdObjectState, access: HouseholdAccessFacts, now: number): HouseholdReadResult;
