// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
export declare const TODO_QUEUE_LIMIT = 200;
export declare const TODO_OPEN_LIMIT = 1000;
export declare const TODO_TITLE_LIMIT = 200;
export declare const TODO_NOTES_LIMIT = 4000;
export declare const TODO_COMMENT_LIMIT = 4000;
export declare const TODO_MENTIONS_LIMIT = 8;
export declare const TODO_GATE_NOTE_LIMIT = 200;
export declare const TODO_EVENT_BYTE_LIMIT: number;
export declare const TODO_IDENTITY_WRITE_HOURLY_LIMIT = 600;
export declare const TODO_WORKSPACE_WRITE_HOURLY_LIMIT = 2000;
export declare const WORK_RECENT_MS: number;
export declare const TODO_DEFAULT_ACCEPTS_FROM: "owner";
export type AgentWork = 'working' | 'idle' | 'disconnected';
/** Server-normalized credential facts. For local agents, connection is live
 * while either a credential or a renewal approval is live. Message age alone
 * never changes connection. All timestamps come from recorded server actions. */
export interface AgentWorkFacts {
    transport: 'local' | 'hosted_mcp';
    turn_only: boolean;
    connection: 'live' | 'removed' | 'key_off' | 'key_ended' | 'paused';
    last_activity_at: string | null;
    messages_waiting_since: string | null;
    doing: {
        todo_id: string;
        title: string | null;
        since: string;
    } | null;
    working_on: {
        signal_id: string;
        at: string;
        until: string;
    } | null;
}
export declare function agentWorkState(facts: AgentWorkFacts, now: number): AgentWork;
export declare const TODO_NOTICE_ABOUT_PREFIX = "todo:";
export declare const OBJECT_NOTICE_ABOUT_PREFIX = "object:";
export declare const TODO_NOTICE_BODIES: {
    readonly added: "Added a to-do to your queue.";
    readonly start: "Please start the to-do at the front of your queue.";
    readonly person_offer: "Asks you to take a to-do.";
    readonly agent_offer: "Asks for a to-do for your agent.";
    readonly accepted: "Accepted your to-do request.";
    readonly declined: "Declined your to-do request.";
    readonly mentioned: "Mentioned you in a comment.";
};
export declare function todoNoticeAbout(todoId: string): string;
