// GENERATED by scripts/build-admin-types.mjs; do not hand-edit.
import { EventEnvelope, TaskState } from './events.d.ts';
/** Thrown when the reducer meets an event type it does not know — the client must stop, not skip. */
export declare class UnknownEventTypeError extends Error {
    readonly type: string;
    readonly seq: number;
    constructor(type: string, seq: number);
}
/** Thrown when a stream is malformed (e.g. a non-create event before the task exists). */
export declare class StreamIntegrityError extends Error {
    constructor(message: string);
}
/** Apply one event to the (possibly absent) task state. Returns the next state. */
export declare function reduceTask(prev: TaskState | null, env: EventEnvelope): TaskState;
/** Fold a full (seq-ordered) stream for one task into its final projection. */
export declare function reduceStream(events: readonly EventEnvelope[]): TaskState | null;
