// Household v1 object core. The transactional adapter authenticates, locks,
// loads exact immutable base bytes and verifies staged bytes before deciding.
// It commits events, projections, protected artifacts and audit together.
// This module performs no I/O and is deliberately not exported by index.ts yet.
import { SCHEMA_VERSION } from './events.js';
import { StreamIntegrityError, UnknownEventTypeError } from './reducer.js';
import {
  HOUSEHOLD_LIVE_REVISION_LIMIT, HOUSEHOLD_OBJECT_LIMIT, HOUSEHOLD_STORAGE_BYTE_LIMIT,
  HOUSEHOLD_VERSION_BYTE_LIMIT, householdAccessRefusal, householdWriteLimitReached,
  type HouseholdAccessFacts, type HouseholdContentOperation,
} from './household-object-policy.js';
import {
  HOUSEHOLD_OBJECT_EVENT_TYPES, HOUSEHOLD_OBJECT_TYPES,
  type HouseholdAttribution, type HouseholdBlob, type HouseholdContent,
  type HouseholdDraft, type HouseholdObject, type HouseholdObjectEvent,
  type HouseholdObjectState, type HouseholdOutcome, type HouseholdPatch,
  type HouseholdReceipt, type HouseholdReservation, type HouseholdRevision,
  type HouseholdRevisionRef,
} from './household-object-events.js';

export type HouseholdObjectCommand =
  | { kind: 'create_household_object'; object_id: string; title: string; content: HouseholdContent }
  | { kind: 'update_household_object'; object_id: string; base: HouseholdRevisionRef; patch: HouseholdPatch;
      title?: { before: string; after: string } }
  | { kind: 'reserve_household_upload'; object_id: string; reservation_id: string; expires_at: number;
      change: { kind: 'create'; title: string; content: HouseholdContent }
        | { kind: 'update'; base: HouseholdRevisionRef; patch: HouseholdPatch; title?: { before: string; after: string } } }
  | { kind: 'commit_household_upload'; reservation_id: string; operation: 'create' | 'update' }
  | { kind: 'release_household_upload'; reservation_id: string; operation: 'create' | 'update' };

/** Adapter-verified artifact facts, never a client's size/digest attestation.
 * For list/docs the blob is the canonical encoding of content. For files it is
 * the actual file bytes, with verified metadata in content. No URLs or paths
 * supplied by models are fetched by this core.
 */
export interface HouseholdVerifiedContent {
  workspace_id: string;
  object_id: string;
  revision: HouseholdRevisionRef | null;
  blob: HouseholdBlob;
  content: HouseholdContent;
}

export interface DecideHouseholdObjectContext {
  access: HouseholdAccessFacts;
  now: number;
  command_id: string;
  /** Canonical request hash verified by the adapter, excluding server facts. */
  request_digest: string;
  seq: number;
  event_id: string;
  /** Generated by the server, not a client integer or content hash. */
  revision_token: string;
  draft_id: string;
  /** Includes this workspace's other retained bytes and unpurged names (legacy
   * files/tombstones included), not represented by this new projection yet. */
  other_storage_bytes: number;
  other_object_count: number;
  /** Counts BEFORE this attempt. The adapter charges validated version-create
   * attempts under the same lock, including refusals, but not retry recovery or
   * commit/release of an already charged reservation. */
  identity_write_attempts: number;
  workspace_write_attempts: number;
  /** Exact base snapshots loaded under current authorization. */
  contents: readonly HouseholdVerifiedContent[];
  /** Staged bytes verified by the adapter; commit loads the reservation's blob. */
  prepared: HouseholdVerifiedContent | null;
}

export interface HouseholdObjectDecision {
  outcome: HouseholdOutcome;
  events: readonly HouseholdObjectEvent[];
  replayed: boolean;
}

const EVENT_BYTE_LIMIT = 64 * 1024; // Canonical SWARM-CLOUD §2.1 envelope bound.
const encoder = new TextEncoder();
const own = <T>(map: Readonly<Record<string, T>>, key: string): T | undefined =>
  Object.hasOwn(map, key) ? map[key] : undefined;
const identifier = (value: unknown): value is string => typeof value === 'string' && value.length > 0;
const nonnegative = (value: number): boolean => Number.isSafeInteger(value) && value >= 0;
const opaque = (value: unknown): value is string =>
  typeof value === 'string' && /^[A-Za-z0-9_-]{22,128}$/.test(value);
const digest = (value: unknown): value is string => typeof value === 'string' && /^[a-f0-9]{64}$/.test(value);

function sameRevision(a: HouseholdRevisionRef | null, b: HouseholdRevisionRef | null): boolean {
  return a === null || b === null ? a === b
    : a.workspace_id === b.workspace_id && a.object_id === b.object_id && a.token === b.token;
}

function validBlob(blob: HouseholdBlob): boolean {
  return !!blob && identifier(blob.storage_key) && nonnegative(blob.size_bytes)
    && blob.size_bytes <= HOUSEHOLD_VERSION_BYTE_LIMIT && digest(blob.sha256);
}

function sameBlob(a: HouseholdBlob, b: HouseholdBlob): boolean {
  return a.storage_key === b.storage_key && a.size_bytes === b.size_bytes && a.sha256 === b.sha256;
}

function validContent(content: HouseholdContent): boolean {
  if (!content || typeof content !== 'object') return false;
  switch (content.kind) {
    case 'doc': return typeof content.markdown === 'string';
    case 'file': return identifier(content.name) && identifier(content.media_type);
    case 'list': {
      if (!Array.isArray(content.items)) return false;
      const ids = new Set<string>();
      return content.items.every((item, index) => {
        if (!item || !identifier(item.item_id) || ids.has(item.item_id) || typeof item.text !== 'string'
          || typeof item.checked !== 'boolean' || item.order !== index) return false;
        ids.add(item.item_id);
        return true;
      });
    }
    default: return false;
  }
}

function sameContent(a: HouseholdContent, b: HouseholdContent): boolean {
  if (a.kind !== b.kind) return false;
  if (a.kind === 'doc' && b.kind === 'doc') return a.markdown === b.markdown;
  if (a.kind === 'file' && b.kind === 'file') return a.name === b.name && a.media_type === b.media_type;
  return a.kind === 'list' && b.kind === 'list' && a.items.length === b.items.length
    && a.items.every((item, index) => {
      const other = b.items[index]!;
      return item.item_id === other.item_id && item.text === other.text
        && item.checked === other.checked && item.order === other.order;
    });
}

function attribution(access: HouseholdAccessFacts): HouseholdAttribution {
  const connection = access.credential.kind === 'agent' ? access.credential.connection : null;
  return { ...access.actor, connection_id: connection?.connection_id ?? null, grant_id: connection?.grant_id ?? null };
}

function receiptKey(principal: string, commandId: string): string {
  return JSON.stringify([principal, commandId]);
}

export function emptyHouseholdObjectState(workspaceId: string, streamId: string): HouseholdObjectState {
  if (!identifier(workspaceId) || !identifier(streamId)) throw new RangeError('workspace and stream IDs are required');
  return { workspace_id: workspaceId, stream_id: streamId, last_seq: -1,
    objects: {}, reservations: {}, drafts: {}, receipts: {} };
}

/** Includes ALL history and declarations; no expiry/retirement discounts before
 * an explicit release. A pending create reserves an unpurged-name slot. */
export function householdObjectUsage(state: HouseholdObjectState): { object_count: number; storage_bytes: number } {
  const names = new Set(Object.keys(state.objects));
  let bytes = 0;
  for (const object of Object.values(state.objects)) {
    for (const revision of object.history) bytes += revision.blob.size_bytes;
  }
  for (const reservation of Object.values(state.reservations)) {
    names.add(reservation.object_id);
    bytes += reservation.proposed.size_bytes;
  }
  for (const draft of Object.values(state.drafts)) bytes += draft.proposed.size_bytes;
  return { object_count: names.size, storage_bytes: bytes };
}

/** Apply an explicit patch to its exact base. Before values defeat a stale
 * replacement with a superficially current revision stapled onto it. Splices
 * are non-overlapping UTF-16 offsets into the base, never sequential offsets.
 */
function applyPatch(base: HouseholdContent, patch: HouseholdPatch, blob: HouseholdBlob): HouseholdContent | null {
  if (!patch || patch.kind !== base.kind) return null;
  if (base.kind === 'doc' && patch.kind === 'doc') {
    if (!Array.isArray(patch.splices)) return null;
    let cursor = 0;
    let result = '';
    let previousStart = -1;
    for (const splice of patch.splices) {
      if (!splice || !nonnegative(splice.start) || splice.start > base.markdown.length
        || splice.start < cursor || splice.start <= previousStart
        || typeof splice.before !== 'string' || typeof splice.after !== 'string'
        || base.markdown.slice(splice.start, splice.start + splice.before.length) !== splice.before) return null;
      result += base.markdown.slice(cursor, splice.start) + splice.after;
      cursor = splice.start + splice.before.length;
      previousStart = splice.start;
    }
    return { kind: 'doc', markdown: result + base.markdown.slice(cursor) };
  }
  if (base.kind === 'file' && patch.kind === 'file') {
    return patch.before_sha256 === blob.sha256 && patch.replacement?.kind === 'file'
      && validContent(patch.replacement) ? patch.replacement : null;
  }
  if (base.kind !== 'list' || patch.kind !== 'list' || !Array.isArray(patch.operations)) return null;
  let items = base.items.map((item) => ({ ...item }));
  const used = new Set(items.map((item) => item.item_id));
  for (const operation of patch.operations) {
    if (!operation || !identifier(operation.item_id)) return null;
    const index = items.findIndex((item) => item.item_id === operation.item_id);
    if (operation.kind === 'add') {
      if (used.has(operation.item_id) || typeof operation.text !== 'string' || typeof operation.checked !== 'boolean') return null;
      const after = operation.after_item_id === null ? -1 : items.findIndex((item) => item.item_id === operation.after_item_id);
      if (operation.after_item_id !== null && after === -1) return null;
      items.splice(after + 1, 0, { item_id: operation.item_id, text: operation.text, checked: operation.checked, order: 0 });
      used.add(operation.item_id);
    } else {
      if (index === -1) return null;
      const item = items[index]!;
      if (operation.kind === 'move') {
        if (item.order !== operation.before_order || operation.after_item_id === item.item_id) return null;
        items.splice(index, 1);
        const after = operation.after_item_id === null ? -1 : items.findIndex((other) => other.item_id === operation.after_item_id);
        if (operation.after_item_id !== null && after === -1) return null;
        items.splice(after + 1, 0, item);
      } else if (operation.kind === 'set' || operation.kind === 'remove') {
        if (item.text !== operation.before_text || item.checked !== operation.before_checked) return null;
        if (operation.kind === 'remove') items.splice(index, 1);
        else {
          if (typeof operation.text !== 'string' || typeof operation.checked !== 'boolean') return null;
          items[index] = { ...item, text: operation.text, checked: operation.checked };
        }
      } else return null;
    }
    items = items.map((item, order) => ({ ...item, order }));
  }
  return { kind: 'list', items };
}

function contentFor(ctx: DecideHouseholdObjectContext, revision: HouseholdRevision): HouseholdContent | null {
  const found = ctx.contents.find((fact) => fact.workspace_id === revision.revision.workspace_id
    && fact.object_id === revision.revision.object_id && sameRevision(fact.revision, revision.revision)
    && sameBlob(fact.blob, revision.blob));
  return found && validContent(found.content) && found.content.kind === revision.kind ? found.content : null;
}

export function decideHouseholdObject(
  command: HouseholdObjectCommand,
  state: HouseholdObjectState,
  ctx: DecideHouseholdObjectContext,
): HouseholdObjectDecision {
  const noEvent = (reason: string): HouseholdObjectDecision => ({ outcome: { status: 'refused', reason }, events: [], replayed: false });
  const operation: HouseholdContentOperation = command.kind === 'commit_household_upload' || command.kind === 'release_household_upload'
    ? command.operation : command.kind === 'create_household_object'
      || (command.kind === 'reserve_household_upload' && command.change.kind === 'create') ? 'create' : 'update';
  if (operation !== 'create' && operation !== 'update') return noEvent('invalid_operation');
  // Refuse before inspecting object names, history, drafts or retry results.
  const denied = householdAccessRefusal(ctx.access, state.workspace_id, operation, ctx.now);
  if (denied) return noEvent(denied);
  if (!identifier(ctx.command_id) || !digest(ctx.request_digest) || !identifier(ctx.event_id)
    || !Number.isSafeInteger(ctx.seq) || ctx.seq <= state.last_seq) return noEvent('invalid_command_context');
  const author = attribution(ctx.access);
  const principal = author.principal_id ?? author.user_id;
  const previous = own(state.receipts, receiptKey(principal, ctx.command_id));
  if (previous) return previous.request_digest === ctx.request_digest
    ? { outcome: structuredClone(previous.outcome), events: [], replayed: true }
    : noEvent('request_id_reused');

  const emit = (type: HouseholdObjectEvent['type'], payload: object, outcome: HouseholdOutcome): HouseholdObjectDecision => {
    const receipt: HouseholdReceipt = { principal, command_id: ctx.command_id, request_digest: ctx.request_digest, outcome };
    const event = {
      workspace_id: state.workspace_id, stream_id: state.stream_id, seq: ctx.seq,
      event_id: ctx.event_id, command_id: ctx.command_id, type, schema_version: SCHEMA_VERSION,
      actor_user: author.user_id, actor_agent_principal: author.principal_id, actor_run: author.run_id,
      occurred_at_server: ctx.now, payload: { ...payload, receipt },
    } as HouseholdObjectEvent;
    if (encoder.encode(JSON.stringify(event)).length > EVENT_BYTE_LIMIT) return noEvent('event_too_large');
    return { outcome, events: [structuredClone(event)], replayed: false };
  };
  const refuse = (reason: string): HouseholdObjectDecision => emit('HouseholdObjectCommandRefused', {}, { status: 'refused', reason });
  const usage = householdObjectUsage(state);
  if (!nonnegative(ctx.other_storage_bytes) || !nonnegative(ctx.other_object_count)) return noEvent('quota_facts_invalid');
  const bytes = usage.storage_bytes + ctx.other_storage_bytes;
  const count = usage.object_count + ctx.other_object_count;
  const currentFor = (objectId: string): HouseholdRevision | undefined => own(state.objects, objectId)?.history.at(-1);
  const preparedFor = (objectId: string): HouseholdVerifiedContent | null => {
    const prepared = ctx.prepared;
    return prepared && prepared.workspace_id === state.workspace_id && prepared.object_id === objectId
      && validBlob(prepared.blob) && validContent(prepared.content) ? prepared : null;
  };
  const conflict = (objectId: string, base: HouseholdRevisionRef, proposed: HouseholdBlob,
    reservationId: string | null, title: string): HouseholdObjectDecision => {
    const current = currentFor(objectId)!;
    if (!identifier(ctx.draft_id) || own(state.drafts, ctx.draft_id)) return refuse('draft_id_invalid');
    if (reservationId === null && bytes + proposed.size_bytes > HOUSEHOLD_STORAGE_BYTE_LIMIT) return refuse('storage_quota_reached');
    const draft: HouseholdDraft = { draft_id: ctx.draft_id, workspace_id: state.workspace_id, object_id: objectId,
      base, current: current.revision, proposed, title, kind: ctx.prepared!.content.kind,
      file_metadata: ctx.prepared!.content.kind === 'file' ? ctx.prepared!.content : null,
      owner: author, occurred_at_server: ctx.now, command_id: ctx.command_id };
    return emit('HouseholdDraftPreserved', { draft, reservation_id: reservationId },
      { status: 'conflict', object_id: objectId, current: current.revision, draft_id: draft.draft_id });
  };
  const commit = (objectId: string, title: string, kind: HouseholdContent['kind'], blob: HouseholdBlob,
    base: HouseholdRevisionRef | null, reservationId: string | null): HouseholdObjectDecision => {
    if (!opaque(ctx.revision_token) || Object.values(state.objects).some((object) =>
      object.history.some((revision) => revision.revision.token === ctx.revision_token))) return refuse('revision_token_invalid');
    const revision: HouseholdRevision = { revision: { workspace_id: state.workspace_id, object_id: objectId, token: ctx.revision_token },
      parent: base, title, kind, blob, file_metadata: ctx.prepared!.content.kind === 'file' ? ctx.prepared!.content : null,
      author, occurred_at_server: ctx.now, command_id: ctx.command_id };
    return emit(base === null ? 'HouseholdObjectCreated' : 'HouseholdObjectUpdated',
      { revision, reservation_id: reservationId }, { status: 'committed', object_id: objectId, revision: revision.revision });
  };

  if (command.kind === 'commit_household_upload' || command.kind === 'release_household_upload') {
    const reservation = own(state.reservations, command.reservation_id);
    if (!reservation || reservation.owner.user_id !== author.user_id
      || reservation.owner.principal_id !== author.principal_id
      || reservation.owner.connection_id !== author.connection_id || reservation.owner.grant_id !== author.grant_id) {
      return noEvent('reservation_access_refused');
    }
    if (command.operation !== (reservation.base === null ? 'create' : 'update')) return noEvent('reservation_access_refused');
    if (command.kind === 'release_household_upload') return emit('HouseholdUploadReleased',
      { reservation_id: reservation.reservation_id }, { status: 'released', reservation_id: reservation.reservation_id });
    if (reservation.expires_at <= ctx.now) return refuse('upload_expired');
    const prepared = preparedFor(reservation.object_id);
    if (!prepared || !sameBlob(prepared.blob, reservation.proposed) || prepared.content.kind !== reservation.kind
      || !sameRevision(prepared.revision, reservation.base)
      || (prepared.content.kind === 'file' && (!reservation.file_metadata
        || !sameContent(prepared.content, reservation.file_metadata)))) {
      return refuse('verified_content_required');
    }
    const current = currentFor(reservation.object_id);
    if (reservation.base === null && current) return refuse('object_already_exists');
    if (reservation.base !== null && !sameRevision(reservation.base, current?.revision ?? null)) {
      return conflict(reservation.object_id, reservation.base, reservation.proposed, reservation.reservation_id, reservation.title);
    }
    // Reserved bytes are already counted; recheck the entire locked quota.
    if (bytes > HOUSEHOLD_STORAGE_BYTE_LIMIT || count > HOUSEHOLD_OBJECT_LIMIT) return refuse('storage_quota_reached');
    return commit(reservation.object_id, reservation.title, reservation.kind, reservation.proposed,
      reservation.base, reservation.reservation_id);
  }

  if (householdWriteLimitReached(ctx.identity_write_attempts, ctx.workspace_write_attempts)) return refuse('object_write_rate_limited');
  const objectId = command.object_id;
  if (!identifier(objectId)) return refuse('object_id_invalid');
  const change = command.kind === 'reserve_household_upload' ? command.change
    : command.kind === 'create_household_object' ? { ...command, kind: 'create' as const }
    : { ...command, kind: 'update' as const };
  const prepared = preparedFor(objectId);
  if (!prepared) return refuse('verified_content_required');
  const current = currentFor(objectId);
  let base: HouseholdRevisionRef | null = null;
  let title: string;
  if (change.kind === 'create') {
    if (current || Object.values(state.reservations).some((pending) => pending.object_id === objectId)) return refuse('object_already_exists');
    if (count >= HOUSEHOLD_OBJECT_LIMIT) return refuse('object_quota_reached');
    if (!validContent(change.content) || !sameContent(change.content, prepared.content)) return refuse('verified_content_mismatch');
    title = change.title;
    if (prepared.revision !== null) return refuse('verified_content_mismatch');
  } else {
    if (!current) return refuse('object_not_found');
    if (!change.base || change.base.workspace_id !== state.workspace_id || change.base.object_id !== objectId || !opaque(change.base.token)) {
      return refuse('revision_not_found');
    }
    const historical = own(state.objects, objectId)!.history.find((revision) => sameRevision(revision.revision, change.base));
    if (!historical) return refuse('revision_not_found');
    const content = contentFor(ctx, historical);
    if (!content) return refuse('verified_base_required');
    const proposed = applyPatch(content, change.patch, historical.blob);
    if (!proposed || !sameContent(proposed, prepared.content)) return refuse('patch_base_mismatch');
    if (change.title && (change.title.before !== historical.title || !identifier(change.title.after))) return refuse('patch_base_mismatch');
    title = change.title?.after ?? historical.title;
    base = historical.revision;
    if (!sameRevision(prepared.revision, base)) return refuse('verified_content_mismatch');
    // Preserve the proposal before returning the authorized current revision.
    if (!sameRevision(base, current.revision)) return conflict(objectId, base, prepared.blob, null, title);
  }
  if (!identifier(title)) return refuse('title_invalid');
  if (bytes + prepared.blob.size_bytes > HOUSEHOLD_STORAGE_BYTE_LIMIT) return refuse('storage_quota_reached');
  if (command.kind === 'reserve_household_upload') {
    if (!identifier(command.reservation_id) || own(state.reservations, command.reservation_id)
      || !Number.isFinite(command.expires_at) || command.expires_at <= ctx.now) return refuse('reservation_invalid');
    const reservation: HouseholdReservation = { reservation_id: command.reservation_id, workspace_id: state.workspace_id,
      object_id: objectId, kind: prepared.content.kind, file_metadata: prepared.content.kind === 'file' ? prepared.content : null,
      title, base, proposed: prepared.blob, owner: author,
      created_at_server: ctx.now, expires_at: command.expires_at };
    return emit('HouseholdUploadReserved', { reservation }, { status: 'pending', object_id: objectId, reservation_id: reservation.reservation_id });
  }
  return commit(objectId, title, prepared.content.kind, prepared.blob, base, null);
}

/** Deterministic replay validates continuity rather than trusting projections.
 * Permission is checked at decision/read time against durable current facts;
 * replay must not erase committed history when a member is later revoked. */
export function reduceHouseholdObject(state: HouseholdObjectState, event: HouseholdObjectEvent): HouseholdObjectState {
  if (!(HOUSEHOLD_OBJECT_EVENT_TYPES as readonly string[]).includes(event.type)) throw new UnknownEventTypeError(event.type, event.seq);
  const fail = (reason: string): never => { throw new StreamIntegrityError(`household event at seq ${event.seq}: ${reason}`); };
  if (event.schema_version !== SCHEMA_VERSION || event.workspace_id !== state.workspace_id || event.stream_id !== state.stream_id
    || !Number.isSafeInteger(event.seq) || event.seq <= state.last_seq || !Number.isFinite(event.occurred_at_server)
    || !identifier(event.event_id) || !identifier(event.command_id)
    || encoder.encode(JSON.stringify(event)).length > EVENT_BYTE_LIMIT) fail('invalid envelope');
  if (!event.payload || typeof event.payload !== 'object') fail('missing payload');
  const receipt = event.payload.receipt;
  if (!receipt || receipt.command_id !== event.command_id || receipt.principal !== (event.actor_agent_principal ?? event.actor_user)
    || !identifier(receipt.principal) || !digest(receipt.request_digest) || !receipt.outcome
    || own(state.receipts, receiptKey(receipt.principal, receipt.command_id))) fail('invalid or duplicate receipt');
  const assertAuthor = (author: HouseholdAttribution): void => {
    if (!author || author.user_id !== event.actor_user || author.principal_id !== event.actor_agent_principal
      || author.run_id !== event.actor_run || !identifier(author.user_id)
      || (author.principal_id === null ? author.connection_id !== null || author.grant_id !== null
        : !identifier(author.connection_id) || !identifier(author.grant_id))) fail('invalid attribution');
  };
  const assertRef = (ref: HouseholdRevisionRef, objectId: string): void => {
    if (!ref || ref.workspace_id !== state.workspace_id || ref.object_id !== objectId || !opaque(ref.token)) fail('invalid revision binding');
  };
  const assertMetadata = (kind: string, metadata: HouseholdContent | null): void => {
    if (kind === 'file' ? !metadata || metadata.kind !== 'file' || !validContent(metadata) : metadata !== null) fail('invalid file metadata');
  };
  const release = (id: string | null, objectId: string, base: HouseholdRevisionRef | null, blob: HouseholdBlob): void => {
    if (id === null) return;
    const reservation = own(state.reservations, id);
    if (!reservation || reservation.object_id !== objectId || !sameRevision(reservation.base, base)
      || !sameBlob(reservation.proposed, blob) || reservation.owner.user_id !== event.actor_user
      || reservation.owner.principal_id !== event.actor_agent_principal) fail('reservation does not match');
    delete reservations[id];
  };
  const objects = { ...state.objects };
  const reservations = { ...state.reservations };
  const drafts = { ...state.drafts };
  switch (event.type) {
    case 'HouseholdObjectCreated':
    case 'HouseholdObjectUpdated': {
      const revision = event.payload.revision;
      if (!revision || !revision.revision) fail('missing revision');
      const objectId = revision.revision.object_id;
      assertRef(revision.revision, objectId);
      assertAuthor(revision.author);
      assertMetadata(revision.kind, revision.file_metadata);
      if (!identifier(objectId) || !identifier(revision.title) || !validBlob(revision.blob)
        || !(HOUSEHOLD_OBJECT_TYPES as readonly string[]).includes(revision.kind)
        || revision.command_id !== event.command_id || revision.occurred_at_server !== event.occurred_at_server
        || Object.values(objects).some((object) => object.history.some((old) => old.revision.token === revision.revision.token))) fail('invalid revision');
      const object = own(objects, objectId);
      if (event.type === 'HouseholdObjectCreated') {
        if (object || revision.parent !== null) fail('duplicate create or non-null parent');
        if (Object.values(reservations).some((pending) => pending.object_id === objectId && pending.reservation_id !== event.payload.reservation_id)) fail('name is reserved');
      } else if (!object || object.kind !== revision.kind || !sameRevision(object.history.at(-1)!.revision, revision.parent)) fail('stale or missing parent');
      const outcome = receipt.outcome;
      if (outcome.status !== 'committed' || outcome.object_id !== objectId || !sameRevision(outcome.revision, revision.revision)) fail('commit receipt mismatch');
      if (event.payload.reservation_id !== null) {
        const pending = own(reservations, event.payload.reservation_id);
        if (!pending || pending.expires_at <= event.occurred_at_server || pending.title !== revision.title
          || pending.kind !== revision.kind || pending.owner.connection_id !== revision.author.connection_id
          || pending.owner.grant_id !== revision.author.grant_id
          || (revision.file_metadata && (!pending.file_metadata
            || !sameContent(revision.file_metadata, pending.file_metadata)))) fail('invalid reservation commit');
      }
      release(event.payload.reservation_id, objectId, revision.parent, revision.blob);
      objects[objectId] = { object_id: objectId, kind: revision.kind, history: [...(object?.history ?? []), structuredClone(revision)] };
      break;
    }
    case 'HouseholdUploadReserved': {
      const reservation = event.payload.reservation;
      if (!reservation || reservation.workspace_id !== state.workspace_id || !identifier(reservation.object_id)
        || !identifier(reservation.reservation_id) || own(reservations, reservation.reservation_id)
        || !identifier(reservation.title) || !validBlob(reservation.proposed)
        || !(HOUSEHOLD_OBJECT_TYPES as readonly string[]).includes(reservation.kind)
        || reservation.created_at_server !== event.occurred_at_server
        || !Number.isFinite(reservation.expires_at) || reservation.expires_at <= event.occurred_at_server) fail('invalid reservation');
      assertAuthor(reservation.owner);
      assertMetadata(reservation.kind, reservation.file_metadata);
      const current = own(objects, reservation.object_id)?.history.at(-1);
      if (reservation.base === null) {
        if (current || Object.values(reservations).some((pending) => pending.object_id === reservation.object_id)) fail('duplicate name reservation');
      } else {
        assertRef(reservation.base, reservation.object_id);
        if (!current || !sameRevision(current.revision, reservation.base) || current.kind !== reservation.kind) fail('stale reservation base');
      }
      const outcome = receipt.outcome;
      if (outcome.status !== 'pending' || outcome.object_id !== reservation.object_id || outcome.reservation_id !== reservation.reservation_id) fail('pending receipt mismatch');
      reservations[reservation.reservation_id] = structuredClone(reservation);
      break;
    }
    case 'HouseholdUploadReleased': {
      const reservation = own(reservations, event.payload.reservation_id);
      if (!reservation || reservation.owner.user_id !== event.actor_user || reservation.owner.principal_id !== event.actor_agent_principal
        || receipt.outcome.status !== 'released' || receipt.outcome.reservation_id !== event.payload.reservation_id) fail('invalid release');
      delete reservations[event.payload.reservation_id];
      break;
    }
    case 'HouseholdDraftPreserved': {
      const draft = event.payload.draft;
      if (!draft || draft.workspace_id !== state.workspace_id || !identifier(draft.draft_id) || own(drafts, draft.draft_id)
        || !identifier(draft.title) || !validBlob(draft.proposed) || draft.command_id !== event.command_id || draft.occurred_at_server !== event.occurred_at_server) fail('invalid draft');
      assertAuthor(draft.owner);
      if (!(HOUSEHOLD_OBJECT_TYPES as readonly string[]).includes(draft.kind)) fail('invalid draft kind');
      assertMetadata(draft.kind, draft.file_metadata);
      assertRef(draft.base, draft.object_id);
      assertRef(draft.current, draft.object_id);
      const object = own(objects, draft.object_id);
      if (!object || object.kind !== draft.kind || !sameRevision(object.history.at(-1)!.revision, draft.current) || sameRevision(draft.base, draft.current)
        || !object.history.some((revision) => sameRevision(revision.revision, draft.base))) fail('invalid conflict history');
      const outcome = receipt.outcome;
      if (outcome.status !== 'conflict' || outcome.object_id !== draft.object_id || outcome.draft_id !== draft.draft_id
        || !sameRevision(outcome.current, draft.current)) fail('conflict receipt mismatch');
      if (event.payload.reservation_id !== null) {
        const pending = own(reservations, event.payload.reservation_id);
        if (!pending || pending.owner.connection_id !== draft.owner.connection_id || pending.owner.grant_id !== draft.owner.grant_id
          || pending.title !== draft.title || pending.kind !== draft.kind) fail('invalid reserved draft');
      }
      release(event.payload.reservation_id, draft.object_id, draft.base, draft.proposed);
      drafts[draft.draft_id] = structuredClone(draft);
      break;
    }
    case 'HouseholdObjectCommandRefused':
      if (receipt.outcome.status !== 'refused' || !identifier(receipt.outcome.reason)) fail('invalid refusal');
      break;
  }
  const next: HouseholdObjectState = { ...state, objects, reservations, drafts, last_seq: event.seq,
    receipts: { ...state.receipts, [receiptKey(receipt.principal, receipt.command_id)]: structuredClone(receipt) } };
  const usage = householdObjectUsage(next);
  if (usage.object_count > HOUSEHOLD_OBJECT_LIMIT || usage.storage_bytes > HOUSEHOLD_STORAGE_BYTE_LIMIT) fail('quota invariant violated');
  return next;
}

export function reduceHouseholdObjectStream(
  events: readonly HouseholdObjectEvent[], initial: HouseholdObjectState,
): HouseholdObjectState {
  return events.reduce(reduceHouseholdObject, initial);
}

export type HouseholdReadQuery =
  | { kind: 'object_list'; offset: number; limit: number }
  | { kind: 'object_read'; object_id: string; revision?: HouseholdRevisionRef }
  | { kind: 'object_history'; object_id: string; offset: number; limit: number }
  | { kind: 'draft_read'; draft_id: string };

export type HouseholdReadResult =
  | { status: 'refused'; reason: string }
  | { status: 'ok'; kind: 'object_list'; objects: readonly { object_id: string; kind: HouseholdContent['kind']; title: string; revision: HouseholdRevisionRef }[]; next_offset: number | null }
  | { status: 'ok'; kind: 'object_read'; revision: HouseholdRevision; live: boolean }
  | { status: 'ok'; kind: 'object_history'; revisions: readonly (HouseholdRevision & { live: boolean })[]; next_offset: number | null }
  | { status: 'ok'; kind: 'draft_read'; draft: HouseholdDraft };

/** Authorized read MODEL only. Byte routes must recheck these same facts at use,
 * then load the returned immutable blob. A reference is not a transfer token.
 * Pagination limits are provided by the measured adapter; v1 does not invent
 * unmeasured read/egress limits. No counts or names leak before authorization.
 */
export function readHouseholdObjects(
  query: HouseholdReadQuery, state: HouseholdObjectState, access: HouseholdAccessFacts, now: number,
): HouseholdReadResult {
  const refusal = householdAccessRefusal(access, state.workspace_id, 'read', now);
  if (refusal) return { status: 'refused', reason: refusal };
  if (query.kind === 'object_list' || query.kind === 'object_history') {
    if (!nonnegative(query.offset) || !Number.isSafeInteger(query.limit) || query.limit <= 0) return { status: 'refused', reason: 'invalid_page' };
  }
  if (query.kind === 'object_list') {
    const all = Object.values(state.objects).sort((a, b) => a.object_id < b.object_id ? -1 : a.object_id > b.object_id ? 1 : 0);
    return { status: 'ok', kind: query.kind, objects: all.slice(query.offset, query.offset + query.limit).map((object) => {
      const revision = object.history.at(-1)!;
      return { object_id: object.object_id, kind: object.kind, title: revision.title, revision: structuredClone(revision.revision) };
    }), next_offset: query.offset + query.limit < all.length ? query.offset + query.limit : null };
  }
  if (query.kind === 'draft_read') {
    const draft = own(state.drafts, query.draft_id);
    if (!draft || draft.owner.user_id !== access.actor.user_id
      || (access.credential.kind === 'agent' && (draft.owner.principal_id !== access.actor.principal_id
        || draft.owner.grant_id !== access.credential.connection.grant_id
        || draft.owner.connection_id !== access.credential.connection.connection_id))) return { status: 'refused', reason: 'draft_access_refused' };
    return { status: 'ok', kind: query.kind, draft: structuredClone(draft) };
  }
  const object: HouseholdObject | undefined = own(state.objects, query.object_id);
  if (!object) return { status: 'refused', reason: 'object_not_found' };
  const liveStart = Math.max(0, object.history.length - HOUSEHOLD_LIVE_REVISION_LIMIT);
  if (query.kind === 'object_history') return { status: 'ok', kind: query.kind,
    revisions: object.history.slice(query.offset, query.offset + query.limit).map((revision, index) => ({
      ...structuredClone(revision), live: query.offset + index >= liveStart,
    })), next_offset: query.offset + query.limit < object.history.length ? query.offset + query.limit : null };
  const index = query.revision ? object.history.findIndex((revision) => sameRevision(revision.revision, query.revision!)) : object.history.length - 1;
  if (index < 0) return { status: 'refused', reason: 'revision_not_found' };
  return { status: 'ok', kind: query.kind, revision: structuredClone(object.history[index]!), live: index >= liveStart };
}
