-- Forward catalog for 20261001000002.
-- Safe OID lookups: missing objects yield false, not a regclass cast error.
WITH expected(name,columns,can_update,pk_count,fk_count,check_count,unique_count) AS (VALUES
  ('admin_created_workspaces',ARRAY['workspace_id','grant_id','scope_names']::text[],false,1,2,0,0),
  ('admin_routine_invitations',ARRAY['invitation_id','workspace_id','parent_admin_grant_id','owner_user_id','recipient_user_id','recipient_connection_id','invitation_kind','expires_at','created_at','revoked_at','accepted_at','projection']::text[],true,1,4,4,0)
), table_state AS (
 SELECT e.*, c.oid, c.relowner, c.relkind, c.relrowsecurity, c.relforcerowsecurity
 FROM expected e LEFT JOIN pg_class c ON c.oid=to_regclass('swarm.'||e.name)
)
SELECT
  COALESCE((
    (SELECT count(*)=2 AND bool_and(oid IS NOT NULL AND relkind='r'
    AND pg_get_userbyid(relowner)='swarm_admin' AND relrowsecurity AND NOT relforcerowsecurity
    AND (SELECT array_agg(a.attname::text ORDER BY a.attnum) FROM pg_attribute a
      WHERE a.attrelid=t.oid AND a.attnum>0 AND NOT a.attisdropped)=t.columns
    AND (SELECT count(*) FROM pg_constraint WHERE conrelid=t.oid AND contype='p')=pk_count
    AND (SELECT count(*) FROM pg_constraint WHERE conrelid=t.oid AND contype='f')=fk_count
    AND (SELECT count(*) FROM pg_constraint WHERE conrelid=t.oid AND contype='c')=check_count
    AND (SELECT count(*) FROM pg_constraint WHERE conrelid=t.oid AND contype='u')=unique_count
    AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid=t.oid AND NOT convalidated)
    AND NOT EXISTS (SELECT 1 FROM pg_index WHERE indrelid=t.oid AND (NOT indisvalid OR NOT indisready))
    AND NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=t.oid AND attnum>0 AND NOT attisdropped AND attacl IS NOT NULL)
    AND (SELECT count(*) FROM pg_policy WHERE polrelid=t.oid)=1
    AND EXISTS (SELECT 1 FROM pg_policy WHERE polrelid=t.oid AND polname='swarm_command_all'
      AND polpermissive AND polcmd='*' AND polroles=ARRAY[(SELECT oid FROM pg_roles WHERE rolname='swarm_command')]
      AND pg_get_expr(polqual,polrelid)='true' AND pg_get_expr(polwithcheck,polrelid)='true')
    AND has_table_privilege('swarm_command',oid,'SELECT')
    AND has_table_privilege('swarm_command',oid,'INSERT')
    AND has_table_privilege('swarm_command',oid,'UPDATE')=can_update
    AND NOT has_table_privilege('swarm_command',oid,'DELETE')
    AND NOT has_table_privilege('swarm_command',oid,'TRUNCATE')
    AND NOT has_table_privilege('swarm_command',oid,'REFERENCES')
    AND NOT has_table_privilege('swarm_command',oid,'TRIGGER')
    AND NOT EXISTS (SELECT 1 FROM aclexplode(coalesce((SELECT relacl FROM pg_class WHERE oid=t.oid),acldefault('r',relowner))) acl WHERE acl.grantee=0)
    AND NOT EXISTS (SELECT 1 FROM (VALUES ('swarm_read'),('anon'),('authenticated')) AS r(name)
      WHERE has_table_privilege(r.name,oid,'SELECT') OR has_table_privilege(r.name,oid,'INSERT')
        OR has_table_privilege(r.name,oid,'UPDATE') OR has_table_privilege(r.name,oid,'DELETE')
        OR has_table_privilege(r.name,oid,'TRUNCATE') OR has_table_privilege(r.name,oid,'REFERENCES')
        OR has_table_privilege(r.name,oid,'TRIGGER'))
  ) FROM table_state t)
    AND (SELECT count(*) FROM pg_attribute WHERE attrelid=to_regclass('swarm.events') AND attnum>0 AND NOT attisdropped AND NOT attnotnull AND (attname::text,atttypid) IN (('admin_identity_id','uuid'::regtype),('grant_id','uuid'::regtype),('grant_manifest_digest','text'::regtype))) = 3
    AND (SELECT count(*) FROM pg_attribute WHERE attrelid=to_regclass('swarm.agent_principals') AND attnum>0 AND NOT attisdropped AND NOT attnotnull AND (attname::text,atttypid) IN (('parent_admin_grant_id','uuid'::regtype))) = 1
    AND (SELECT count(*) FROM pg_attribute WHERE attrelid=to_regclass('swarm.agent_tokens') AND attnum>0 AND NOT attisdropped AND NOT attnotnull AND (attname::text,atttypid) IN (('parent_admin_grant_id','uuid'::regtype),('recipient_connection_id','uuid'::regtype))) = 2
    AND EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid=to_regclass('swarm.events') AND conname='delegated_event_actor' AND contype='c' AND convalidated)
    AND EXISTS (SELECT 1 FROM pg_index i WHERE i.indexrelid=to_regclass('swarm.admin_routine_invitations_owner_created') AND i.indrelid=to_regclass('swarm.admin_routine_invitations') AND i.indisvalid AND i.indisready AND i.indisunique=false AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(i.indkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=i.indrelid AND a.attnum=k.num)=ARRAY['owner_user_id','created_at']::text[] AND i.indpred IS NULL)
    AND (SELECT p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql') AND p.pronargdefaults=0 AND pg_get_userbyid(p.proowner)='swarm_admin' AND p.prosecdef = true AND p.provolatile='v' AND p.proconfig = ARRAY['search_path=pg_catalog']::text[] AND p.proretset = false AND p.prorettype='boolean'::regtype AND has_function_privilege('swarm_command',p.oid,'EXECUTE') AND has_function_privilege('swarm_read',p.oid,'EXECUTE') AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND NOT has_function_privilege('authenticated',p.oid,'EXECUTE') AND NOT EXISTS (SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND md5(p.prosrc)='365b41eac2ea26a138b63f94c9b4a5fa' FROM pg_proc p WHERE p.oid=to_regprocedure('swarm.admin_child_live(uuid,uuid)'))
    AND (SELECT p.prolang=(SELECT oid FROM pg_language WHERE lanname='sql') AND p.pronargdefaults=0 AND pg_get_userbyid(p.proowner)='swarm_admin' AND p.prosecdef = true AND p.provolatile IN ('s','v') AND p.proconfig = ARRAY['search_path=pg_catalog']::text[] AND p.proretset = false AND p.prorettype='boolean'::regtype AND has_function_privilege('swarm_command',p.oid,'EXECUTE') AND has_function_privilege('swarm_read',p.oid,'EXECUTE') AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND NOT has_function_privilege('authenticated',p.oid,'EXECUTE') AND NOT EXISTS (SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND md5(p.prosrc)='e5129b4f01f6a53bcdc336bbc006f157' FROM pg_proc p WHERE p.oid=to_regprocedure('swarm.admin_child_scopes_live(uuid,jsonb)'))
    AND (SELECT p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql') AND p.pronargdefaults=0 AND pg_get_userbyid(p.proowner)='swarm_admin' AND p.prosecdef = true AND p.provolatile='v' AND p.proconfig = ARRAY['search_path=pg_catalog']::text[] AND p.proretset = false AND p.prorettype='trigger'::regtype AND NOT has_function_privilege('swarm_command',p.oid,'EXECUTE') AND NOT has_function_privilege('swarm_read',p.oid,'EXECUTE') AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND NOT has_function_privilege('authenticated',p.oid,'EXECUTE') AND NOT EXISTS (SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND md5(p.prosrc)='db6999b8c3ff1373bae0414c7837ae7a' FROM pg_proc p WHERE p.oid=to_regprocedure('swarm.admin_token_ancestry()'))
    AND (SELECT p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql') AND p.pronargdefaults=0 AND pg_get_userbyid(p.proowner)='swarm_admin' AND p.prosecdef = false AND p.provolatile='v' AND p.proconfig = ARRAY['search_path=pg_catalog']::text[] AND p.proretset = false AND p.prorettype='trigger'::regtype AND NOT has_function_privilege('swarm_command',p.oid,'EXECUTE') AND NOT has_function_privilege('swarm_read',p.oid,'EXECUTE') AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND NOT has_function_privilege('authenticated',p.oid,'EXECUTE') AND NOT EXISTS (SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND md5(p.prosrc)='3936f9615baaedb748c016e7dd2edaf2' FROM pg_proc p WHERE p.oid=to_regprocedure('swarm.admin_principal_ancestry()'))
    AND (SELECT p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql') AND p.pronargdefaults=0 AND pg_get_userbyid(p.proowner)='swarm_admin' AND p.prosecdef = true AND p.provolatile='v' AND p.proconfig = ARRAY['search_path=pg_catalog']::text[] AND p.proretset = false AND p.prorettype='trigger'::regtype AND NOT has_function_privilege('swarm_command',p.oid,'EXECUTE') AND NOT has_function_privilege('swarm_read',p.oid,'EXECUTE') AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND NOT has_function_privilege('authenticated',p.oid,'EXECUTE') AND NOT EXISTS (SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) acl WHERE acl.grantee=0 AND acl.privilege_type='EXECUTE') AND md5(p.prosrc)='b8609292dc40178bdf562a109ef84fa0' FROM pg_proc p WHERE p.oid=to_regprocedure('swarm.admin_end_pending_invitations()'))
    AND EXISTS (SELECT 1 FROM pg_policy WHERE polrelid=to_regclass('swarm.agent_tokens') AND polname='admin_parent_select' AND NOT polpermissive AND polcmd='r' AND polroles @> ARRAY[(SELECT oid FROM pg_roles WHERE rolname='swarm_command'),(SELECT oid FROM pg_roles WHERE rolname='swarm_read')] AND cardinality(polroles)=2)
    AND EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid=to_regclass('swarm.agent_tokens') AND tgname='aa_admin_token_ancestry' AND NOT tgisinternal AND tgenabled='O' AND tgfoid=to_regprocedure('swarm.admin_token_ancestry()') AND tgtype=23)
    AND EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid=to_regclass('swarm.agent_principals') AND tgname='admin_principal_ancestry' AND NOT tgisinternal AND tgenabled='O' AND tgfoid=to_regprocedure('swarm.admin_principal_ancestry()') AND tgtype=19)
    AND EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid=to_regclass('swarm.admin_grants') AND tgname='admin_end_pending_invitations' AND NOT tgisinternal AND tgenabled='O' AND tgfoid=to_regprocedure('swarm.admin_end_pending_invitations()') AND tgtype=17)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_created_workspaces') AND attname='workspace_id' AND NOT attisdropped AND atttypid='uuid'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_created_workspaces') AND attname='grant_id' AND NOT attisdropped AND atttypid='uuid'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_created_workspaces') AND attname='scope_names' AND NOT attisdropped AND atttypid='text[]'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.admin_created_workspaces') AND contype='p' AND convalidated AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.conkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.num)=ARRAY['workspace_id']::text[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.admin_created_workspaces') AND contype='f' AND convalidated AND confrelid=to_regclass('swarm.workspaces') AND confupdtype='a' AND confdeltype='a' AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.conkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.num)=ARRAY['workspace_id']::text[] AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.confkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.num)=ARRAY['workspace_id']::text[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.admin_created_workspaces') AND contype='f' AND convalidated AND confrelid=to_regclass('swarm.admin_grants') AND confupdtype='a' AND confdeltype='a' AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.conkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.num)=ARRAY['grant_id']::text[] AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.confkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.num)=ARRAY['grant_id']::text[])
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='invitation_id' AND NOT attisdropped AND atttypid='uuid'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='workspace_id' AND NOT attisdropped AND atttypid='uuid'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='parent_admin_grant_id' AND NOT attisdropped AND atttypid='uuid'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='owner_user_id' AND NOT attisdropped AND atttypid='uuid'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='recipient_user_id' AND NOT attisdropped AND atttypid='uuid'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='recipient_connection_id' AND NOT attisdropped AND atttypid='uuid'::regtype AND attnotnull=false)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='invitation_kind' AND NOT attisdropped AND atttypid='text'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='expires_at' AND NOT attisdropped AND atttypid='timestamptz'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='created_at' AND NOT attisdropped AND atttypid='timestamptz'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='revoked_at' AND NOT attisdropped AND atttypid='timestamptz'::regtype AND attnotnull=false)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='accepted_at' AND NOT attisdropped AND atttypid='timestamptz'::regtype AND attnotnull=false)
    AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid=to_regclass('swarm.admin_routine_invitations') AND attname='projection' AND NOT attisdropped AND atttypid='jsonb'::regtype AND attnotnull=true)
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.admin_routine_invitations') AND contype='p' AND convalidated AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.conkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.num)=ARRAY['invitation_id']::text[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.admin_routine_invitations') AND contype='f' AND convalidated AND confrelid=to_regclass('swarm.workspaces') AND confupdtype='a' AND confdeltype='a' AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.conkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.num)=ARRAY['workspace_id']::text[] AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.confkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.num)=ARRAY['workspace_id']::text[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.admin_routine_invitations') AND contype='f' AND convalidated AND confrelid=to_regclass('swarm.admin_grants') AND confupdtype='a' AND confdeltype='a' AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.conkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.num)=ARRAY['parent_admin_grant_id']::text[] AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.confkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.num)=ARRAY['grant_id']::text[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.admin_routine_invitations') AND contype='f' AND convalidated AND confrelid=to_regclass('swarm.users') AND confupdtype='a' AND confdeltype='a' AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.conkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.num)=ARRAY['owner_user_id']::text[] AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.confkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.num)=ARRAY['user_id']::text[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.admin_routine_invitations') AND contype='f' AND convalidated AND confrelid=to_regclass('swarm.users') AND confupdtype='a' AND confdeltype='a' AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.conkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.num)=ARRAY['recipient_user_id']::text[] AND (SELECT array_agg(a.attname::text ORDER BY k.ord) FROM unnest(c.confkey) WITH ORDINALITY k(num,ord) JOIN pg_attribute a ON a.attrelid=c.confrelid AND a.attnum=k.num)=ARRAY['user_id']::text[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.events') AND contype='f' AND convalidated AND confrelid=to_regclass('swarm.admin_grants') AND conkey=ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid=c.conrelid AND attname='grant_id' AND NOT attisdropped)]::smallint[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.agent_principals') AND contype='f' AND convalidated AND confrelid=to_regclass('swarm.admin_grants') AND conkey=ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid=c.conrelid AND attname='parent_admin_grant_id' AND NOT attisdropped)]::smallint[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE conrelid=to_regclass('swarm.agent_tokens') AND contype='f' AND convalidated AND confrelid=to_regclass('swarm.admin_grants') AND conkey=ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid=c.conrelid AND attname='parent_admin_grant_id' AND NOT attisdropped)]::smallint[])
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid=to_regclass('swarm.admin_routine_invitations') AND c.contype='c' AND c.convalidated AND pg_get_constraintdef(c.oid) LIKE '%invitation_kind%' AND pg_get_constraintdef(c.oid) LIKE '%member%' AND pg_get_constraintdef(c.oid) LIKE '%agent%')
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid=to_regclass('swarm.admin_routine_invitations') AND c.contype='c' AND c.convalidated AND pg_get_constraintdef(c.oid) LIKE '%expires_at > created_at%')
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid=to_regclass('swarm.admin_routine_invitations') AND c.contype='c' AND c.convalidated AND pg_get_constraintdef(c.oid) LIKE '%jsonb_typeof(projection)%' AND pg_get_constraintdef(c.oid) LIKE '%object%')
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid=to_regclass('swarm.admin_routine_invitations') AND c.contype='c' AND c.convalidated AND pg_get_constraintdef(c.oid) LIKE '%agent%' AND pg_get_constraintdef(c.oid) LIKE '%recipient_connection_id IS NOT NULL%')
    AND EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid=to_regclass('swarm.events') AND c.contype='c' AND c.convalidated AND pg_get_constraintdef(c.oid) LIKE '%grant_id IS NULL%' AND pg_get_constraintdef(c.oid) LIKE '%admin_identity_id IS NOT NULL%' AND pg_get_constraintdef(c.oid) LIKE '%grant_manifest_digest ~%' AND pg_get_constraintdef(c.oid) LIKE '%^[0-9a-f]{64}$%' AND pg_get_constraintdef(c.oid) LIKE '%actor_user IS NULL%' AND pg_get_constraintdef(c.oid) LIKE '%actor_agent_principal IS NULL%' AND pg_get_constraintdef(c.oid) LIKE '%actor_run IS NULL%')
    AND EXISTS (SELECT 1 FROM pg_policy WHERE polrelid=to_regclass('swarm.agent_tokens') AND polname='admin_parent_select' AND pg_get_expr(polqual,polrelid) LIKE '%admin_child_scopes_live(parent_admin_grant_id, scopes)%' AND pg_get_expr(polqual,polrelid) LIKE '%admin_child_live(parent_admin_grant_id,%' AND pg_get_expr(polqual,polrelid) LIKE '%workspace_id%' AND pg_get_expr(polqual,polrelid) LIKE '%agent_tokens.principal_id%')
    AND EXISTS (SELECT 1 FROM pg_trigger t WHERE tgrelid=to_regclass('swarm.admin_grants') AND tgname='admin_end_pending_invitations' AND ARRAY(SELECT unnest(t.tgattr))=ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid=t.tgrelid AND attname='state' AND NOT attisdropped)]::smallint[])
  ), false) AS catalog_ok
\gset
