// GENERATED by read/build-admin-recovery.mjs from src/cloud/admin-delegations-contract.ts; do not hand-edit.
/** Human recovery views. No credential records or arbitrary event payloads. */
export const ADMIN_RECOVERY_RESOURCE = "https://api.commonswarm.com/admin";
export const ADMIN_PAGE_MAX = 100;
export const ADMIN_PAGE_DEFAULT = 50;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;
export interface AdminGrantView {
  grant_id: string;
  admin_identity_id: string;
  connection_id: string;
  client_id: string;
  mode: "granular" | "full_account";
  scope_names: string[];
  workspace_selector: "selected" | "owned_and_selected";
  workspace_ids: string[];
  withdrawn_workspace_ids: string[];
  created_at: string;
  expires_at: string;
  state: "active" | "suspended" | "revoked" | "expired";
  reason_code: string | null;
}
export interface AdminActionView {
  seq: string;
  event_id: string;
  occurred_at_server: string;
  grant_id: string | null;
  admin_identity_id: string | null;
  actor_user: string | null;
  action: string;
  target_kind: string;
  target_id: string | null;
  workspace_id: string | null;
  outcome: "accepted" | "refused" | "pending" | "failed";
  reason_code: string | null;
  next_action: string;
  recovery_kind: string;
  related_event_ids: string[];
}
export type AdminReadRequest = ({ resource: "admin_grants" } | { resource: "admin_history" }) & {
  workspace_id: string | null;
  limit: number;
  before: string | null;
};
export interface AdminRecoveryPage {
  grants: AdminGrantView[];
  actions: AdminActionView[];
  next_before: string | null;
  active: {
    grant_count: number;
    full_account_count: number;
    expires_at: string | null;
    full_account_expires_at: string | null;
  };
}
/** Remove terminal controls and bidi overrides; browser callers still use textContent. */
export function adminDisplayText(value: string): string {
  return value.replace(/[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/gu, " ").slice(0, 2048);
}
export function adminReadRequest(value: unknown): AdminReadRequest | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const r = value as Record<string, unknown>;
  if (Object.keys(r).length !== 4 || !["resource", "workspace_id", "limit", "before"].every(k => Object.hasOwn(r, k)) ||
      (r.resource !== "admin_grants" && r.resource !== "admin_history") ||
      (r.workspace_id !== null && (typeof r.workspace_id !== "string" || !UUID.test(r.workspace_id))) ||
      !Number.isInteger(r.limit) || Number(r.limit) < 1 || Number(r.limit) > ADMIN_PAGE_MAX ||
      (r.before !== null && !validAdminCursor(r.before))) return null;
  return { resource: r.resource, workspace_id: typeof r.workspace_id === "string" ? r.workspace_id.toLowerCase() : null,
    limit: Number(r.limit), before: r.before as string | null };
}
export function validAdminCursor(value: unknown): value is string {
  if (typeof value !== "string") return false;
  const parts = value.split("|");
  return parts.length === 2 && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(parts[0]!) &&
    Number.isFinite(Date.parse(parts[0]!)) && new Date(parts[0]!).toISOString() === parts[0] && UUID.test(parts[1]!);
}
function record(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("CommonSwarm returned an unreadable admin view.");
  return value as Record<string, unknown>;
}
function text(value: unknown, nullable = false): string | null {
  if (nullable && value === null) return null;
  if (typeof value !== "string" || value.length > 2048) throw new Error("CommonSwarm returned an invalid admin field.");
  return adminDisplayText(value);
}
function identifier(value: unknown, nullable = false): string | null {
  if (nullable && value === null) return null;
  if (typeof value !== "string" || !UUID.test(value)) throw new Error("CommonSwarm returned an invalid admin identifier.");
  return value.toLowerCase();
}
function timestamp(value: unknown, nullable = false): string | null {
  if (nullable && value === null) return null;
  if (typeof value !== "string" || value.length > 40 || !Number.isFinite(Date.parse(value))) throw new Error("CommonSwarm returned an invalid admin time.");
  return new Date(value).toISOString();
}
function array<T>(value: unknown, parse: (v: unknown) => T): T[] {
  if (!Array.isArray(value) || value.length > ADMIN_PAGE_MAX) throw new Error("CommonSwarm returned an oversized admin view.");
  return value.map(parse);
}
function grant(value: unknown): AdminGrantView {
  const r = record(value);
  if ((r.mode !== "granular" && r.mode !== "full_account") ||
      !["active", "revoked", "suspended", "expired"].includes(String(r.state)) ||
      (r.workspace_selector !== "selected" && r.workspace_selector !== "owned_and_selected")) throw new Error("CommonSwarm returned an invalid admin grant state.");
  return { grant_id: identifier(r.grant_id)!, admin_identity_id: identifier(r.admin_identity_id)!, connection_id: identifier(r.connection_id)!,
    client_id: text(r.client_id)!, mode: r.mode, scope_names: array(r.scope_names, v => text(v)!), workspace_selector: r.workspace_selector,
    workspace_ids: array(r.workspace_ids, v => identifier(v)!), withdrawn_workspace_ids: array(r.withdrawn_workspace_ids, v => identifier(v)!),
    created_at: timestamp(r.created_at)!, expires_at: timestamp(r.expires_at)!, state: r.state as AdminGrantView["state"], reason_code: text(r.reason_code, true) };
}
function action(value: unknown): AdminActionView {
  const r = record(value);
  if (typeof r.seq !== "string" || !/^[1-9][0-9]{0,18}$/u.test(r.seq) ||
      !["accepted", "refused", "pending", "failed"].includes(String(r.outcome))) throw new Error("CommonSwarm returned an invalid admin action.");
  return { seq: r.seq, event_id: identifier(r.event_id)!, occurred_at_server: timestamp(r.occurred_at_server)!,
    grant_id: identifier(r.grant_id, true), admin_identity_id: identifier(r.admin_identity_id, true), actor_user: identifier(r.actor_user, true),
    action: text(r.action)!, target_kind: text(r.target_kind)!, target_id: identifier(r.target_id, true), workspace_id: identifier(r.workspace_id, true),
    outcome: r.outcome as AdminActionView["outcome"], reason_code: text(r.reason_code, true), next_action: text(r.next_action)!,
    recovery_kind: text(r.recovery_kind)!, related_event_ids: array(r.related_event_ids, v => identifier(v)!) };
}
/** Select the public fields again at the client boundary; never print a raw server body. */
export function parseAdminRecoveryPage(value: unknown): AdminRecoveryPage {
  const r = record(value), a = record(r.active);
  const count = (v: unknown): number => {
    if (typeof v !== "number" || !Number.isSafeInteger(v) || v < 0) throw new Error("CommonSwarm returned invalid active grant counts.");
    return v;
  };
  if (r.next_before !== null && !validAdminCursor(r.next_before)) throw new Error("CommonSwarm returned an invalid admin page cursor.");
  return { grants: array(r.grants, grant), actions: array(r.actions, action), next_before: r.next_before as string | null,
    active: { grant_count: count(a.grant_count), full_account_count: count(a.full_account_count),
      expires_at: timestamp(a.expires_at, true), full_account_expires_at: timestamp(a.full_account_expires_at, true) } };
}
